### ISSUE TITLE
Choppy framerate

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#100]
The framerate is really fast, but it is kinda choppy. We should limit fps.

**Comment by maximusvladimir** [comment]
Additionally some clients have noticed poor speeds on their platforms.

**Comment by maximusvladimir** [comment]
Seems to have gotten worse.

**Comment by abauer** [comment]
status on this now?

**Comment by maximusvladimir** [comment]
I think it has gotten really nice on my computer; I need to check on some other people's though.

**Comment by abauer** [comment]
im ready to test, recently after these updates the framerate is fine. Unfortunately I believe this needs to be left open as a reminder to consistently check this / fix this as we add more features

**Comment by maximusvladimir** [comment]
Okey dokey.

**Comment by maximusvladimir** [comment]
Linked to issue #106.

**Comment by maximusvladimir** [comment]
Has anybody else found this to be true?

@DarkWarHero @Matthis5point0 @TexasGamer @abauer @smeagle42

**Comment by abauer** [comment]
mine seems fine atm

**Comment by maximusvladimir** [comment]
Well my question is, is it faster than it was a few days ago?

**Comment by maximusvladimir** [comment]
This is a continuous issue. Closing for now. Expect to see it later.
