### ISSUE TITLE
Rivers are weird

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#101]
Issues fixed
- [x] Sometimes rivers generate in oceans, causing the oceans to appear weird.
- [x] Rivers are small and awkward looking.
- [x] Rivers only go in _one direction_. That's what happens when five guys work on an extra-curricular activity.

**Comment by maximusvladimir** [comment]
lol. Did anybody get the joke?

**Comment by ThomasGaubert** [comment]
;)

**Comment by abauer** [comment]
yep

**Comment by maximusvladimir** [comment]
Bumped.
