### ISSUE TITLE
Game update issue

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#102]
I thought about this before, but I am thinking that this is more of an issue than I originally asserted it to be.

Picture this:

What if someone named Bob was playing the game, and Bob saved his game and the game that he was playing had ships and ports and stuff, and then he went to update the game. When hr went and updated, everything loaded properly, high scores and stuff all worked properly (thanks to roketgamer), but when he went to play the game that he was in the middle of, something strange happened. It turned out we updated the world generator, and since the game only saves the seed, the grid (entities), stats, AI, and scores, some of the ships were on land, and some of the ports were in the water.

What should we do in this scenario?
1. Not let clients (Bob) update his game until they/he finishes all open games. (Sounds good)
2. Warn clients (Bob) that when they/he update(s) their/his game there could be issues that could be brought up (it would only be for updates that modify the world gen or grid). (Sounds okay)
3. Delete their games, saying they are incompatible. (Yikes)
4. Write some kind of conversion script for each update, that some how keeps part of the world generator code. (Too much effort)
5. ??? (Something else maybe?)

**Comment by ThomasGaubert** [comment]
Option 1 would be interesting to enforce, so option 2 seems like the best bet. We can always have a "download old version" button with the warning.

**Comment by maximusvladimir** [comment]
That's what I am thinking for now. We aren't going to have to worry too much about this right now, but I seriously doubt we will be doing a lot of updating for the terrain generator once we start rolling out playable versions of the game.

**Comment by abauer** [comment]
need to prevent submitting scores from games started in a previous version

**Comment by ThomasGaubert** [comment]
You can either check that client side (if its out of date force offline mode) or create a new leaderboard in the RoketGamer control panel online for every version and change the leaderboard name in the code.

**Comment by maximusvladimir** [comment]
Scores aren't up to me. I don’t understand how they work, and I don’t want to understand. It is up to y’all for that. I don’t know what we will be scoring, all I know is that we are using RoketGamer.

**Comment by ThomasGaubert** [comment]
Alright.

**Comment by maximusvladimir** [comment]
@abauer I think you wanted to suggest something here.

**Comment by abauer** [comment]
1
basically say that you can finish your game now, or you can update, the server would keep track of which version the game was finished under, thus determining that some versions can be differently scored and the leader boards would be fair.

**Comment by ThomasGaubert** [comment]
That's easy enough to do, just save the version with the save game file and send the version to the server for handling.

**Comment by maximusvladimir** [comment]
The way I am looking at it, this is a 1.0 issue.

**Comment by abauer** [comment]
@TexasGamer yes that was the point
@Matthis5point0 agree

**Comment by ThomasGaubert** [comment]
Wrong tag?

**Comment by abauer** [comment]
idk

**Comment by maximusvladimir** [comment]
Was this ever fixed?

**Comment by ThomasGaubert** [comment]
Not in code yet, but the plan would be to not submit scores that are created using an older version of the game (checked with the new BroadcastService class).

Eventually RoketGamer might get support for version tracking across leaderboards. However, that would be post-launch with a new version of the API.

**Comment by maximusvladimir** [comment]
Oh ok.

**Comment by ThomasGaubert** [comment]
This has been handled...
