### ISSUE TITLE
Grid system needs partial rewrite

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#103]
To make entities bigger than 50x50 pixels, we need to partially rewrite and organise the grid subsystem.
- [x] Cleanup code.
- [x] Write image utility methods.
- [x] Separate NavalBattle code from EntityManager (OOP).
- [ ] Possibly move entity rendering from chunks to global system. (Not recommended, but might be necessary).
- [x] Add tiles.

**Comment by maximusvladimir** [comment]
I believe we have finished the rewrite.

**Comment by abauer** [comment]
not all checked?

**Comment by maximusvladimir** [comment]
"(Not recommended, but might be necessary)." it turns out I didn't need to do it.
