### ISSUE TITLE
Game Scope and Progress

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#105]
I will embellish this more this afternoon, but basically we need to work on the actual game ASAP and need to drop ideas (for version 1.0 at least) until then.

_Stay tuned..._

**Comment by maximusvladimir** [comment]
Ageed. Until we launch the proposal that I made, I don't think the game can go anywhere. But I kinda need a break this week...

**Comment by ThomasGaubert** [comment]
Okay, that's fine. Ideally we should be done with the renderer by February 10th (long weekend to actually do work).

**Comment by ThomasGaubert** [comment]
This was addressed a while ago.
