### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#106]
Some clients and testers are noticing lags and jagged movement.

**Comment by maximusvladimir** [comment]
Linked with issue #100.

**Comment by maximusvladimir** [comment]
This should be fixed. We need to test it and make sure.

**Comment by abauer** [comment]
agreed

**Comment by maximusvladimir** [comment]
Does anybody know why Matt is assigned this?

**Comment by maximusvladimir** [comment]
Does anybody else agree to have another thread dedicated for input processing and buffer writing? (the Game may use 75% CPU, but it will be really nice and smooth.)

**Comment by ThomasGaubert** [comment]
> Does anybody know why Matt is assigned this?

No idea.

> Does anybody else agree to have another thread dedicated for input processing and buffer writing? (the Game may use 75% CPU, but it will be really nice and smooth.)

Sure, if it's doable.

**Comment by maximusvladimir** [comment]
After Matt fixes whatever, this issue will be transferred to issue #167.

**Comment by ThomasGaubert** [comment]
I really don't know why this is open still (let alone assigned to Matt) :/

**Comment by maximusvladimir** [comment]
Ok then I guess since there is nothing that @Matthis5point0 needs to do, this can be closed for now.
