### ISSUE TITLE
System UI and Feel

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#11]
Custom system UI and Feel

**Comment by ThomasGaubert** [comment]
This will need to be evaluated in the near future as the window system is changing.

**Comment by maximusvladimir** [comment]
Not a big priority.

**Comment by ThomasGaubert** [comment]
Agreed. I'll close it for now and if this needs to be done it can be re-opened.

**Comment by ThomasGaubert** [comment]
Mostly fixed, though the UI needs to be resized for this new look.

**Comment by abauer** [comment]
fixed and working nicely
