### ISSUE TITLE
NavalBattle activity

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#112]
The memory usage on NavalBattle looks like shark fins (kinda). Maybe this is an omen sying we should add sharks to the game:

![image](https://f.cloud.github.com/assets/1757519/100203/0a0b11d4-67f5-11e2-88ca-6e7cfe881e49.png)

**Comment by ThomasGaubert** [comment]
No, we aren't adding sharks until higher priority features are added.

Neat easter egg though.

**Comment by maximusvladimir** [comment]
Yeah this is more of an easter egg/ joke.
