### ISSUE TITLE
Rotatable Entities

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#113]
Entities should be able to be rotated north, south, east, or west.

This comprises of tracking the Entities logically within the engine and displaying the appropriate image on the screen (image rotation utility or individual images for each orientation).

Animations are not necessary and not under the scope of this issue.

**Comment by maximusvladimir** [comment]
Agreed. Could we put this in 0.6 though?

**Comment by abauer** [comment]
no because 0.6 has issues that rely on this working now

**Comment by ThomasGaubert** [comment]
:+1:

**Comment by maximusvladimir** [comment]
Linked to issue #120.

**Comment by ThomasGaubert** [comment]
This is two days overdue. This needs to be fixed ASAP.

For everyday we are behind, it's less time to work on future milestones. Due dates won't change.

**Comment by maximusvladimir** [comment]
It took me a while to do it, but its finished. Wo!
