### ISSUE TITLE
Entity events are not implemented.

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#114]
The following has been implemented.
- [x] onMouseMove(int x, int y) - when the mouse is moving over the entity.
- [x] onMove(Location original) - when the entity has moved. Original is the original location.
- [x] onMouseDown(int x, int y, boolean leftClick) - when the mouse has been pressed on the entity.The boolean is true, when the left mouse button is pressed. It is false when the right button is pressed. If another button is pressed, it will return false.
- [ ] onHit(Entity attackingEntity) - when the entity has been hit by another entity (is this referring to an attack or ship-to-ship collision?).
- [ ] onAttack(Entity entityBeingAttacked) - when the current entity is being attacked.
- [x] onUpdate() - when the entity is being updated.\

**Comment by maximusvladimir** [comment]
The first four should be done by 0.5. The rest will be done later.

**Comment by maximusvladimir** [comment]
Added onMouseMove as of commit id d89cd756579aa5bc02521cee27d1a78da04b8a12.

**Comment by abauer** [comment]
kewl

**Comment by maximusvladimir** [comment]
Added onMouseDown as of commit id d63f0938d598feb0cd8882e36fd6ce893c0abb41.
