### ISSUE TITLE
Add GameKit to build path

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#115]
We will be adding GameKit to the NavalBattle project soon. You will need to add GameKit to your NavalBattle build path by doing the following:
1. Clone (download) GameKit via GitHub and set up in Eclipse as usual
2. Right click on the NavalBattle project in Eclipse
3. Select "Properties"
4. Select "Java Build Path"
5. Select "Projects" tab
6. Press the "Add" button
7. Select GameKit

Currently we do not depend on GameKit, but we will soon. If you don't do this (one time set up!) you will eventually get errors. Ask me if you have any questions!

attn: @DarkWarHero @Matthis5point0 @abauer @smeagle42 @maximusvladimir

**Comment by maximusvladimir** [comment]
I believe everybody has done this.
