### ISSUE TITLE
Grid moves

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#116]
The first chuck moves left and right as the screen is moved left and right, front two columns disappear and reappear

**Comment by maximusvladimir** [comment]
I thought we had this as an issue already. Oh well. (This has been know about since v0.2ish).

**Comment by ThomasGaubert** [comment]
Marked as milestone blocker since this is critical.

**Comment by maximusvladimir** [comment]
Why is this critical?

**Comment by ThomasGaubert** [comment]
Because the game isn't rendering correctly, defeating the purpose of the rest of the grid work?

**Comment by maximusvladimir** [comment]
"The first chuck moves left and right..." - crap. How many Chuck Norrises are there???

**Comment by maximusvladimir** [comment]
The grid is still working, the system just believes that those chunks are not on the screen.

**Comment by abauer** [comment]
ok so when will this be fixed? doesn;t sound like a hard fix if the program's logic is sound

**Comment by maximusvladimir** [comment]
It probably won't take me very long, but I don't wanna do it yet.

**Comment by abauer** [comment]
ok kewl

**Comment by maximusvladimir** [comment]
Fixed, but some weird stuff occurs do to the fix. Now I remember why I never fixed it in the first place...

**Comment by ThomasGaubert** [comment]
What? o.o

**Comment by maximusvladimir** [comment]
Oh so I had to revert something, but it deleted the whale images I made, so I had to revert it again.

**Comment by ThomasGaubert** [comment]
So it's still fixed? Hooray double negatives!

**Comment by maximusvladimir** [comment]
Haha yeah.

**Comment by abauer** [comment]
thats a little wierd... lol
