### ISSUE TITLE
Add Pavo to build path

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#117]
We will be adding Pavo to the NavalBattle project soon. You will need to add Pavo to your NavalBattle build path by doing the following:
1. Clone (download) Pavo via GitHub and set up in Eclipse as usual
2. Right click on the NavalBattle project in Eclipse
3. Select "Properties"
4. Select "Java Build Path"
5. Select "Projects" tab
6. Press the "Add" button
7. Select Pavo

Currently we do not depend on Pavo, but we will soon. If you don't do this (one time set up!) you will eventually get errors. Ask me if you have any questions!

attn: @DarkWarHero @Matthis5point0 @abauer @smeagle42 @TexasGamer

**Comment by maximusvladimir** [comment]
Pavo is clearly not ready. I don't plan on migrating it any time soon.

**Comment by abauer** [comment]
do you agree: it is doubtful this is migrating

**Comment by maximusvladimir** [comment]
I was going to close soon anyways. It's fine.
