### ISSUE TITLE
Ships should appear on the grid

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#119]
When a user clicks a Ship should appear on the grid space at that location. For testing purposes only

**Comment by maximusvladimir** [comment]
Like TankTest, except on click and only on water?

**Comment by ThomasGaubert** [comment]
Sure

**Comment by abauer** [comment]
yes something along those lines

**Comment by maximusvladimir** [comment]
I can do that right now.

**Comment by maximusvladimir** [comment]
It has been done.

**Comment by abauer** [comment]
kewl
