### ISSUE TITLE
Ships should be able to rotate

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#120]
On a Right Click ships should rotate around their bow.

**Comment by ThomasGaubert** [comment]
Not animated, of course.

**Comment by maximusvladimir** [comment]
Like I have said before, I know how to animate and rotate them, and how to store it, I just don't understand how to approach it yet. Give me a few more weeks to do this.

**Comment by ThomasGaubert** [comment]
Uh, okay... good luck!

**Comment by maximusvladimir** [comment]
(I was implying that we should move the milestone for this issue) :wink:

**Comment by abauer** [comment]
nah lets leave it on this one

**Comment by maximusvladimir** [comment]
(This milestone may take a very long time to complete...)

**Comment by abauer** [comment]
you have 10 days...

**Comment by maximusvladimir** [comment]
Does somebody else want to do rotating?

**Comment by abauer** [comment]
not entirely but i can try it if you want help

**Comment by maximusvladimir** [comment]
Excellent. This task is now assigned to @abauer.

**Comment by abauer** [comment]
give me a run-down of what your ideas are

**Comment by maximusvladimir** [comment]
Umm well I would start with loading rotated images, and then overriding Entity.java and name it RotatableEntity.

**Comment by maximusvladimir** [comment]
Linked to issue #113.

**Comment by ThomasGaubert** [comment]
This is two days overdue. This needs to be fixed ASAP.

For everyday we are behind, it's less time to work on future milestones. Due dates won't change.

**Comment by maximusvladimir** [comment]
Merged with #113
