### ISSUE TITLE
Grid Functionality

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#122]
The Grid should be finalized and finished

Entites need the following methods added and working fully:
- [x] moveTo(a location)
- [x] rotateTo(an orientation)
- [x] hide() (now is moveTo(Location.Unknown)).

**Comment by maximusvladimir** [comment]
I don't understand what this means. Won't we be done with the grid in version 1.0? Even then we will probably still be adding features and entities, etc.

**Comment by ThomasGaubert** [comment]
We need to have Grid functionality that is good enough (for now) for everything outlined in 0.5.

More features can be added as needed, of course, but we need the basics working flawlessly.

**Comment by maximusvladimir** [comment]
Oh ok, so this is just the foundation that y'all want.

**Comment by abauer** [comment]
as @TexasGamer  said, but not limited to 0.5, maybe through 0.6 or 0.7 if possible; because yes it is a foundation

**Comment by ThomasGaubert** [comment]
Correct!

**Comment by maximusvladimir** [comment]
Ok.

**Comment by maximusvladimir** [comment]
So what methods for the Grid and entities would y'all like to see? I added some above.
