### ISSUE TITLE
Land and Water Determined

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#123]
The game engine should be able to deductively infer which tiles are land and which tiles are water. This means 100% reliability in decisions.

**Comment by ThomasGaubert** [comment]
In my opinion, water grid spaces have 100% water and land grid places have > 0% of land.

Areas with a certain amount of land (so little to where it is hard to distinguish if the tile is land or water) should be reverted to 100% water for clarity's sake.

The engine could also be less liberal in its distribution of land (no really tiny islands).

**Comment by maximusvladimir** [comment]
We can't safely modify the internal workings of the engine, without something catastrophic occurring (e.g. too much land, too much water, too many waves, land appearing unnatural, etc). I have tuned everything just about right (there will be more water in the game soon). Also there is going to be significantly more rivers, lakes, forests, etc soon (0.6ish).

**Comment by abauer** [comment]
ok but the way i see this is as follows: Each tile has a percentage of land vs water. Currently there are random tiles in the ocean that have land on them but look like water; this needs to be fixed. I don't care if you have to remove sand, i would perfer not but whatever makes the water work better needs to happen.

**Comment by maximusvladimir** [comment]
I am taking data from numbers and turning it into color. The percent thing is based on numbers, not colors.

**Comment by abauer** [comment]
i know; but we need to refine it because some land-masses pop up in the middle of the ocean

**Comment by maximusvladimir** [comment]
Well in the real world, such as Hawaii, things like that happen, so they should stay.

**Comment by abauer** [comment]
yes but Hawaii is a distinct island, it should be visible

**Comment by maximusvladimir** [comment]
Well my point was is that it is a random, fairly small island sitting out in the middle of no where.

**Comment by maximusvladimir** [comment]
I am pretty sure this is fixed as of commit id 4cc5bd9c5edfcbc1e2cc3cbd43875d7f3533242f.
