### ISSUE TITLE
Turn System

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#125]
Turns should be implemented and ships should move on a turn basis (only certain number of spaces)

**Comment by maximusvladimir** [comment]
Status on this?

**Comment by ThomasGaubert** [comment]
I thought you were working on it?

**Comment by maximusvladimir** [comment]
No... This is Anthony (I think).

![tr](http://cdn.memegenerator.net/instances/25x/35836582.jpg)

**Comment by abauer** [comment]
no you defiantly committed stuff concerning this and told us you would take care of it

**Comment by maximusvladimir** [comment]
I was committing base ideas. I am not in-charge of turn based development.

**Comment by abauer** [comment]
ok first step (should have done this awhile ago) is to identify what a turn basis is and what it affects. A turn basis is a way of limiting what happens to a turn basis; therefore identifying what needs limiting is the 2nd step

**Comment by abauer** [comment]
- [x] Entity Movement Limit
- [x] Entity Attack Limit
- [x] Player Shop Limit
- etc. (add here please)

**Comment by abauer** [comment]
the work needed for 0.6 has been completed, work left has been moved with this milestone to 0.7

**Comment by abauer** [comment]
ugg attacks....

**Comment by ThomasGaubert** [comment]
Marked attack limit as complete. (this is separate from damage, etc.)

**Comment by abauer** [comment]
its not though, im not limitng the times you can attacks

**Comment by ThomasGaubert** [comment]
Ah, whoops.

**Comment by abauer** [comment]
shops are added in 0.8, this issues has been moved to 0.8 to accommodate

**Comment by abauer** [comment]
pretty sure this is complete
