### ISSUE TITLE
Ships Move

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#126]
Well they actually sail but...

**Comment by ThomasGaubert** [comment]
Related to #109 (not a duplicate)

**Comment by maximusvladimir** [comment]
I believe that 109 and 126 are not related. 109 is referring to the glitches and bugs associated with it.

**Comment by ThomasGaubert** [comment]
Hmm... true.

**Comment by abauer** [comment]
what max has this down

**Comment by abauer** [comment]
so #109  is related to the Move.to method, this is more-related to the turn system as ships need to move on a turn basis.

**Comment by maximusvladimir** [comment]
Can this be closed now?

**Comment by ThomasGaubert** [comment]
I think this includes the selecting of the ship and moving it to a spot highlighted (in range). In that case, no.

**Comment by maximusvladimir** [comment]
Hahaha I can do zat.

![Star Trek](http://24.media.tumblr.com/tumblr_ljv7cl4MLp1qa51o3o1_500.gif)

**Comment by abauer** [comment]
well they have moved for quite awhile...
