### ISSUE TITLE
Movement range should be highlighted on ship selection

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#127]

**Comment by ThomasGaubert** [comment]
Also take into account land.

**Comment by maximusvladimir** [comment]
Tiles that you can move to would be green, tiles that you cannot move to would be red.

**Comment by ThomasGaubert** [comment]
Or not colored at all as "attackable" tiles will be red, possibly. Whatever uses less resources :P

**Comment by maximusvladimir** [comment]
Too much effort.

**Comment by abauer** [comment]
well i think the highlighting needs to occur based on action type, for example if the action is movement, tiles are colored movement range, if action is attack then attack range needs to be highlighted

**Comment by maximusvladimir** [comment]
Thats how I thought it was going to work.

**Comment by abauer** [comment]
ok cool

**Comment by maximusvladimir** [comment]
We need #125 to be done, for this feature to work.

**Comment by maximusvladimir** [comment]
This has been added as of commit id eab46feb80ed7b9f1c982f3b8e4ac346f0342fed.
