### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#128]
Ships should be able to be selected and other useful data should appear on a HUD

**Comment by ThomasGaubert** [comment]
@smeagle42 can design icons and what not.

**Comment by abauer** [comment]
- [x] Attack
- [x] score
- [x] diplomacy
- [x] move

**Comment by maximusvladimir** [comment]
- [x] Time of day - text indicator

**Comment by abauer** [comment]
- [x] missiles
- [x] guns
- [x] location
- [x] health
- [x] movement/attack range

**Comment by maximusvladimir** [comment]
I believe that this should probably be moved. There's a lot to do, and much of it depends on stuff that has yet to exist.

**Comment by ThomasGaubert** [comment]
The point of the HUD in this milestone (AFAIK, @abauer please correct me if I'm wrong) is to have the placeholders for all of the buttons and at least have the turn system working with the HUD (movement range, moves left, press to advance to next turn, etc.).

In that case, it cannot be moved.

**Comment by maximusvladimir** [comment]
Ok understood. I thought y'all wanted all of the above features implemented in this milestone.

**Comment by abauer** [comment]
basically the turn system issue closed and a draft for the buttons is all that is required; AFTER both of those are done we can 'copy' (by moving) this issue to the next milestone for fine-tuning

**Comment by smeagle42** [comment]
We should make it so whenever you click on a ship, the highlighted area only is on water instead of a square.

**Comment by abauer** [comment]
what does this mean, it already does this, and also that't not entirely part of the HUD

**Comment by ThomasGaubert** [comment]
Yeah this is the wrong issue for that, but basically he is saying that the valid movement highlight should only be for water tiles (and not both land and water).

**Comment by abauer** [comment]
I like it how it is.. it tells you where your movement range falls and which tiles are valid and which are not...

**Comment by maximusvladimir** [comment]
Technically, it would be slightly faster for non-highlighted areas, if they weren't red. I kinda like the red though.

**Comment by abauer** [comment]
honestly either way works for me

**Comment by abauer** [comment]
the work needed for 0.6 has been completed, work left has been moved with this milestone to 0.7

**Comment by abauer** [comment]
ok so just need String update display and the 'h' key lock option (requires gamekit integration of windows)
