### ISSUE TITLE
Basic AI

### ISSUE THREAD

**Issue by JVetus** [JPII/NavalBattle#129]
AI should be able to move and attack

**Comment by ThomasGaubert** [comment]
Feel free to post your thoughts on the AI algorithm here @DarkWarHero (and others).

**Comment by maximusvladimir** [comment]
Recommended approach: A\* algorithm (pronounced a-star).

**Comment by ThomasGaubert** [comment]
FYI, @DarkWarHero http://en.wikipedia.org/wiki/A*_search_algorithm

**Comment by ThomasGaubert** [comment]
We should have a draft of the AI algorithm within the coming weeks, right?

**Comment by abauer** [comment]
i would hope...

**Comment by ThomasGaubert** [comment]
_cough_ @DarkWarHero

**Comment by ThomasGaubert** [comment]
Approximately how close are we to a basic AI?

cc: @DarkWarHero

**Comment by abauer** [comment]
I feel that we can close this issue because this is an ongoing issue and the AI will be one of the main focus's until we are at a feature lock

**Comment by maximusvladimir** [comment]
Does it work? (To an extent?)

**Comment by abauer** [comment]
is an ongoing issue

Basically, what will be done, will be done and it cannot be qualified until it is complete

**Comment by maximusvladimir** [comment]
I kinda have my computer running, but I am going to run more repairs on it. As soon as I am done, I will probably start working on this issue.

**Comment by ThomasGaubert** [comment]
Wrong issue @maximusvladimir ?

**Comment by maximusvladimir** [comment]
Yeah. :smile:

**Comment by ThomasGaubert** [comment]
Closed.
