### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#13]
When executing, random null pointer exception
This is caused by swing threading on different, invisible threads... can be solved with invokeandwait()

**Comment by ThomasGaubert** [comment]
Confirmed.

@maximusvladimir is investigating.

**Comment by abauer** [comment]
keep going @maximusvladimir ! almost finished!

**Comment by ThomasGaubert** [comment]
@abauer @DarkWarHero @Matthis5point0 @maximusvladimir @smeagle42 

Milestone 0.1 is due tomorrow (August 29th). This bug is **critical** and needs to be fixed ASAP.

**Comment by ThomasGaubert** [comment]
Moved to Milestone Alpha 0.2 (Typhoon). The bug isn't affecting the operation of the program, but is still **critical**.

Must be fixed ASAP (this weekend most likely) and will not be moved to another milestone after this.
