### ISSUE TITLE
Ports implemented

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#130]

**Comment by abauer** [comment]
status on this?

**Comment by ThomasGaubert** [comment]
_cough_

**Comment by maximusvladimir** [comment]
Is a cold going around? _cough_ . Ummm well I thought this was done.

**Comment by ThomasGaubert** [comment]
Uh we didn't do what we discussed on the board yet (as far as I can see)

**Comment by abauer** [comment]
can we put that on github for records? im assuming your meaning stuff like this;
- [ ] Separate Shop system
- [ ] Regular Shop system
- [ ] Team Color
- [ ] Score per turn
- [ ] Captureable

**Comment by abauer** [comment]
these may rely on other issues to be fixed first (StatusBar and Score)

**Comment by abauer** [comment]
Shop, via turn-basis; and damage value adjustments;

**Comment by maximusvladimir** [comment]
Anthony is this fixed.

**Comment by abauer** [comment]
this item discussed in this issue that do not directly relate to ports have been moved, and the issues relating to ports is complete, therefore this issue is closed...
