### ISSUE TITLE
Submarines implemented

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#132]

**Comment by maximusvladimir** [comment]
Anybody could add an entity. It is really simple:
1. Insure that the entity images are added and the sizes are multiple of 50's.
2. Create a class for "the Entity".
3. Have "the Entity" inherit Entity.
4. Overload the constructor.
5. Overload the init() method. Place setWidth(submarine image width / 50); and setHeight(subamrine image height / 50); in the init() method.
6. Register the newly made entity in the EntityManager. This is done by calling registerEntity(<path to image>); once.
7. Construct a new entity. This would be done like so: "new MyEntity(this,new Location(0,0),myEntityId);"
8. You're done!

**Comment by ThomasGaubert** [comment]
Special feature will be the submerged and surfaced states.

**Comment by abauer** [comment]
understood, just it needs to happen sometime

**Comment by maximusvladimir** [comment]
Wait what?

**Comment by abauer** [comment]
this issue is just a reminder to put submarines in the game at this milestone

**Comment by maximusvladimir** [comment]
Oh ok.

**Comment by abauer** [comment]
definitely have been implemented...

**Comment by ThomasGaubert** [comment]
Completely? With the submerged and surfaced toggle?

**Comment by abauer** [comment]
um... urmmm... um...

**Comment by ThomasGaubert** [comment]
:shipit:

**Comment by ThomasGaubert** [comment]
Are states toggleable yet?

**Comment by abauer** [comment]
yes; there is no button but the code is already there
