### ISSUE TITLE
Economy System

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#133]
- [x] Shop implementation
- [x] Upgrades
- [x] Points
- [x] Spending points
- [x] Health
- [x] etc.

**Comment by abauer** [comment]
Updated

**Comment by abauer** [comment]
BOOST!!! window on the way

**Comment by maximusvladimir** [comment]
Boooooosht.

**Comment by ThomasGaubert** [comment]
From our planning session at the board:

**Scoring**
- Sink ship - 500
- Complete stage - 200
- Deflect attack - 50
- Force sub to surface (< 25% HP) - 100
- Bonus points (post launch) - n/a

**Port Shops**
- Battleship - tabled
- Submarine - tabled
- Aircraft Carrier - tabled
- Repair port - 400

**Ship Shop**
- Repair - 300
- Missiles (x5) - 250
- Range (+1, max 3) - 700
- Anti-missile - 350
- Hull upgrade (+100% current health, +100% max health, -50% move range) - 200

**Comment by abauer** [comment]
#237 for stage completion

**Comment by abauer** [comment]
HUD check for secondary avaliablity

**Comment by abauer** [comment]
Ship shop check for AC

**Comment by abauer** [comment]
#140 for Port upgrades

**Comment by abauer** [comment]
done with this
