### ISSUE TITLE
Advanced AI

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#135]

**Comment by ThomasGaubert** [comment]
From today's notes in regards to diplomacy:
- Cost
- Should enact diplomacy?
- Duration of diplomacy (or constant)

cc: @DarkWarHero

**Comment by maximusvladimir** [comment]
I'm almost thinking, if we have time, there should be a strategy for the AI too.

**Comment by ThomasGaubert** [comment]
Possibly, but lets keep it relatively simple and polished first.

**Comment by ThomasGaubert** [comment]
@DarkWarHero 

What else needs to be completed?

**Comment by ThomasGaubert** [comment]
Finished!
