### ISSUE TITLE
Attack System

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#139]

**Comment by abauer** [comment]
Ai classes should extend Player class and then redefine the attack, move, diplomacy, shop (etc.) methods

**Comment by maximusvladimir** [comment]
Can AI shop for food, ships, etc?

**Comment by ThomasGaubert** [comment]
Food?

And yeah, the AI should be able to buy items and what not. We can decide if it needs a score handicap (so it always makes money).

**Comment by abauer** [comment]
So what does this issue require to complete / move forward; the system should be complete, but the AI itself may not be finished.

**Comment by abauer** [comment]
@maximusvladimir @DarkWarHero @TexasGamer (above comment)

**Comment by ThomasGaubert** [comment]
If everything like damage, keeping track of weapons/attack count, etc. is working then we are good.

**Comment by abauer** [comment]
you can only attack once a turn, not attack teammates... and damage really sin't implemented becasue we don't know what damage to apply (fill out the damage calculator table)

**Comment by ThomasGaubert** [comment]
Attack once per turn per weapon, right? (I can use both guns and missiles once on a single turn)

**Comment by ThomasGaubert** [comment]
If so, then it looks good to me :+1:

**Comment by abauer** [comment]
yes
