### ISSUE TITLE
Finalize Ports

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#140]
In conjunction with Economy

**Comment by abauer** [comment]
need to be capture-able / attackable

**Comment by maximusvladimir** [comment]
Please tag/label appropriately, so Max will see when he is looking for a list of things to do.

**Comment by abauer** [comment]
still not sure if i will take this one on; so let it be

**Comment by maximusvladimir** [comment]
Ok.

**Comment by abauer** [comment]
ability to spawn battleships, aircraft carriers, submarines. and repair / health (part of the capture-able system)

**Comment by abauer** [comment]
ok here is what needs to be done
- [x] caputre-able (via health)
- [x] attack able (DamageCalculator)
- [ ] spawn entities out of
- [x] repairable

**Comment by abauer** [comment]
i can start on this but @maximusvladimir needs to close his other issues

**Comment by abauer** [comment]
just need spawning

**Comment by abauer** [comment]
anybody know the algorithm / how-to code it for spawning ships? I have an idea but not sure how to implement

**Comment by ThomasGaubert** [comment]
Possibly adapt the ship move algorithm to determine a spot that can fit a ship?

**Comment by ThomasGaubert** [comment]
Finally done (commit coming soon).
