### ISSUE TITLE
Double clicking a tile should center the screen on it.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#143]

**Comment by abauer** [comment]
is this something todo? or is this an issue

**Comment by maximusvladimir** [comment]
Todo

**Comment by abauer** [comment]
name was confusing, updated

**Comment by maximusvladimir** [comment]
Ok.

**Comment by maximusvladimir** [comment]
I'm confused about this.

**Comment by ThomasGaubert** [comment]
What part about it?

**Comment by abauer** [comment]
@maximusvladimir what is the status of this as of last class?

**Comment by maximusvladimir** [comment]
Umm well, it works, but you can't provide a grid location yet.

**Comment by ThomasGaubert** [comment]
We decided to close this one. The ability to center the screen will still be added.

**Comment by maximusvladimir** [comment]
Sounds good.
