### ISSUE TITLE
Entity move issue

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#145]
Moving an entity too rapidly may cause parts of it to be temporarily deleted or disfigured. An entity should not be moved more than once every two seconds.

**Comment by abauer** [comment]
well seeing as the only problem may be that the player moving the entity, therefore we can animate it kinda and that would fix this?

**Comment by maximusvladimir** [comment]
![bug](https://dl.dropbox.com/u/11164236/navalbattle/nb0.5_05.png)

**Comment by maximusvladimir** [comment]
There were suppose to be 5 entities there.

**Comment by abauer** [comment]
nice, i assume this is just a visual problem, did it fix itself after screen update or does it stay that way?

**Comment by maximusvladimir** [comment]
It stays that way.

**Comment by abauer** [comment]
then maybe this should be moved to 0.6

**Comment by maximusvladimir** [comment]
Well as of commit id 93e302ae5ac6f9e7178f1feefe045f87e9677d7e, the effects of it are no longer permanent.

**Comment by maximusvladimir** [comment]
Is this still here?

**Comment by maximusvladimir** [comment]
I believe this was fixed thanks to the Anthony Update.

**Comment by abauer** [comment]
np
