### ISSUE TITLE
OmniMap

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#146]
OmniMap should show the player's entities in yellow dots, and other players' in green.

**Comment by abauer** [comment]
friendly vs enemy?

**Comment by maximusvladimir** [comment]
Sure.

**Comment by abauer** [comment]
well considering we don't have a turn basis or an AI (simple AI that stand there) nor do we have a team structure, this should be bumped back until we have those.

**Comment by ThomasGaubert** [comment]
That seems like a good idea.

**Comment by maximusvladimir** [comment]
I didn't realize we were doing this on the current milestone...

**Comment by ThomasGaubert** [comment]
Bumped to 0.7

**Comment by ThomasGaubert** [comment]
Status on this?

**Comment by maximusvladimir** [comment]
I'll do this tonight after dinner.

**Comment by maximusvladimir** [comment]
Actually, more specifically, stir-fry dinner with shrimp.

**Comment by maximusvladimir** [comment]
Changed to cyan dots. Considered it finished for now (there is no way to access a client's entity manager without reaching an MemoryAccessViolationException.
