### ISSUE TITLE
Ship Movement Error

### ISSUE THREAD

**Issue by Matthis5point0** [JPII/NavalBattle#149]
When ships reach the bottom right corner of the grid the ships quit moving when they would move into an era where they would be within 2 tiles on the grid of leaving the drawn grid and going into what max calls the "imaginary world".  This creates an ArrayIndexOutOfBounds Exception when this happens.

**Comment by abauer** [comment]
well thats a good point, this can be solved with a limit to where ships can move, at this stage ships do not move yet...
