### ISSUE TITLE
Sound Effects

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#152]
Basic sound effects, such as firing, etc.

This does not cover music (soundtrack). Please see #151.

**Comment by maximusvladimir** [comment]
One thing that drives me crazy in indie games, is when the sound effects are crackled sounding, or not professional sounding. I believe that we should try to stick to sounds from soundcloud.com or freesound.org.

**Comment by ThomasGaubert** [comment]
I agree 100%. :+1:

**Comment by abauer** [comment]
im not good with this stuff, someone else can handle this but i agree

**Comment by ThomasGaubert** [comment]
Technically falls under @smeagle42  area, I think. Though we can suggest stuff too.

It's low priority anyways...

**Comment by abauer** [comment]
really?

**Comment by ThomasGaubert** [comment]
Yeah, I think so...

**Comment by smeagle42** [comment]
My brother has a soundboard with tons of sound effects on it. I'll see what i can find there for this part. I think we need water splashing sound, gun explosions, ship explosions, motor noise, missile noise, and button clicking. I can make it as professional as the CD recordings so no need to worry i have noise in any and all aspects covered with the best quality available today.

**Comment by ThomasGaubert** [comment]
Okay, if you can work on those and we can edit them as needed that would be great.

**Comment by abauer** [comment]
yeah additionally is it possible to do it twice, since we may not know what we want yet

**Comment by ThomasGaubert** [comment]
Also, FreeSound is a thing.

**Comment by ThomasGaubert** [comment]
I believe we decided to move this to post-launch, correct me if I'm wrong.

**Comment by maximusvladimir** [comment]
"Sounds" good.

**Comment by ThomasGaubert** [comment]
Moved to 0.9 as we probably need some sort of sound for release. Here's what we should aim for:
- Next turn sound - http://www.freesound.org/people/qubodup/sounds/166540/
- Ship hit - http://www.freesound.org/people/Kastenfrosch/sounds/162455/
- Game over - http://www.freesound.org/people/notchfilter/sounds/43698/
- Achievement unlocked - http://www.freesound.org/people/Kastenfrosch/sounds/162467/

I'll post links to some ideas later.

**Comment by ThomasGaubert** [comment]
Status on this, @smeagle42?

We don't need the .ogg format, by the way. Therefore you can use "native" Java code...

**Comment by ThomasGaubert** [comment]
Okay I took care of this, someone aka @smeagle42 implement. You _are_ the sound lead might I add.

**Comment by ThomasGaubert** [comment]
Went ahead and implemented all but the game over sound.
