### ISSUE TITLE
Code Clean-up and Remove Warnings

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#153]
Remove all the warnings and unused code/commented out code

**Comment by maximusvladimir** [comment]
Assigned to Anthony. :wink:

**Comment by abauer** [comment]
hey i have no problem removing all the unused code, you just might loose some stuff...

**Comment by maximusvladimir** [comment]
Ok well technically the old renderer is still in the code (kinda like Giant Zombies in MC).

com.jpii.navalbattle.renderer (I believe it is called), should have been removed a **long** time ago.

There are a few other things that should be removed.

**Comment by abauer** [comment]
Well because max doesn't want all his commented code taken out, we will discuss this further in 0.7

**Comment by maximusvladimir** [comment]
I didn't say that. I said I would like to make a hard copy, before this was done.

**Comment by abauer** [comment]
this one is going to be fun...
Max make your copy before Tuesday

**Comment by ThomasGaubert** [comment]
Yeah, let's not do this until everything else for the milestone is done (obviously). 

Each person can claim a package or two to prevent detached heads...

**Comment by ThomasGaubert** [comment]
Also, we should update copyright headers to 2013. Get with the times!

**Comment by abauer** [comment]
actually, i was going to start tuesday

**Comment by ThomasGaubert** [comment]
Or that. Proceed with caution!

**Comment by abauer** [comment]
ok done removing warnings and comments
