### ISSUE TITLE
Land to Water Ratio

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#154]
Seeing as this is a water based game there is a lot of land generated by the terrain gen; Additionally do we insure that all water is connected, say that a team spawns in a "lake" apart from opponents, how does that team win/loose?

**Comment by maximusvladimir** [comment]
I believe that I commented on something like this in a previous issue. Essentially, the actual game will have much less land. If you saw the Spanish Pirate Mafia Video (v0.0.1 r9), there are only islands that generate in the middle of the map. We might be able to do this in the future.

**Comment by ThomasGaubert** [comment]
You could also run a pathfinding program (similar to the MazeSolver lab) to run from one end of the map to the other.

**Comment by abauer** [comment]
both work, i prefer max's way though, i believe this could work in conjunction with building a base so that's why its in 0.6 milestone

**Comment by maximusvladimir** [comment]
Ok.

**Comment by ThomasGaubert** [comment]
I agree too.

**Comment by maximusvladimir** [comment]
So we are going to go in another direction with this now. We are simply going to melt the ice caps on the world.

**Comment by abauer** [comment]
um ok; so one big island?

**Comment by maximusvladimir** [comment]
No. We are adding ice caps to the world generator, then calling `getWorld().changeWorldTemperature(80)`. That should raise the water level.

(No but seriously, we are going to raise the water level, making the majority of the land water, and a few occasional islands)

**Comment by maximusvladimir** [comment]
So coming in late 0.6, we could possibly see infinite chunks.

**Comment by abauer** [comment]
make a new issue for 1.7, and the game needs to be limited for actual gameplay to prevent running away

**Comment by ThomasGaubert** [comment]
> the game needs to be limited for actual gameplay to prevent running away

thisthisthisthisthisthisthisthisthisthisthisthisthisthisthisthisthisthisthisthisthis

**Comment by maximusvladimir** [comment]
Well this would be a Pavo feature and would be disabled in NB. Also, we had a slight problem, so it has to be bumped to 1.0.

**Comment by abauer** [comment]
little bit different issue but ok

**Comment by maximusvladimir** [comment]
I believe that this is solved, however I would like to see infinite chunks.

**Comment by maximusvladimir** [comment]
![f](http://i.imgflip.com/11ueg.jpg)
