### ISSUE TITLE
Whales aren't removed when ships overlap

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#155]
When adding a ship to the grid, a whale will demolish a portion of the battleship if it is in the way. As far as I know, the whale should disappear instead.

**Comment by maximusvladimir** [comment]
Entities will never overlap each other in the actual game.

If you don't wish for this particular issue to happen, you can use moveTo(r,c,false); (I think).

**Comment by ThomasGaubert** [comment]
I understand that they won't overlap in the actual game, but I thought the entity "rules" were that if a new entity is placed in a location that already contains an entity, the old entity would be removed and replaced with the new one.

**Comment by maximusvladimir** [comment]
What we have is if you set the override method to false, it will not override the entity. Do you want it to be the way that you specified above?

**Comment by ThomasGaubert** [comment]
Uh I haven't tested this, I'll talk to you in person.

**Comment by maximusvladimir** [comment]
Ok. That's fine.

**Comment by abauer** [comment]
so basically i get that ships wont' overlay thus whales don't need to be removed... completed
