### ISSUE TITLE
Ship Animation

### ISSUE THREAD

**Issue by smeagle42** [JPII/NavalBattle#156]
When ships are stationary. They sway back and forth and create waves from it.

**Comment by abauer** [comment]
*should

**Comment by abauer** [comment]
moved to later milestone, this is not appropriate for this milestone (functionality/features)

**Comment by maximusvladimir** [comment]
``` java
                      -------------------
                    /   (Max's head)     \
                  o>                      \
                   /      FEATURES        |
                  /     -------------     /
                 ----   FUNCTIONALITY    /
                    >                   /
                   /___________________/
                         |     |
```

**Comment by ThomasGaubert** [comment]
Marked as on hold.

**Comment by abauer** [comment]
never saw that diagram but that funny

**Comment by maximusvladimir** [comment]
This requires the 1x1 animated entity problem to be fixed, as well as waves to be made for ships.

**Comment by abauer** [comment]
@TexasGamer @maximusvladimir is this still a thing? are we doing this? is this a priority?

**Comment by ThomasGaubert** [comment]
No. This can be re-evaluated post launch.

**Comment by maximusvladimir** [comment]
Agreed.
