### ISSUE TITLE
AnimatedEntity does not operate with Entities bigger than 1x1.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#157]

**Comment by smeagle42** [comment]
The whale animation has stopped working

**Comment by maximusvladimir** [comment]
Well this isn't the right issue, but can you try to let the game run for a while, and see if they eventually start moving?

**Comment by maximusvladimir** [comment]
Zach you are right. Something is broken.

**Comment by abauer** [comment]
Nothing is broken

**Comment by maximusvladimir** [comment]
Nothing is broken now. It was previously.

**Comment by maximusvladimir** [comment]
I believe that this issue might have been taken care of, but we will have to wait tell we get the whales working again before I promise anything.

**Comment by maximusvladimir** [comment]
AnimatedEntities are not a priority. Therefore, it is going to be bumped to 0.8.

**Comment by maximusvladimir** [comment]
I don't think this is an issue anymore.

**Comment by maximusvladimir** [comment]
I don't know though.

**Comment by abauer** [comment]
is this even needed?

**Comment by maximusvladimir** [comment]
I am pretty sure the only reason this issue is opened, is because we need to run a test. Somebody please close this issue.
