### ISSUE TITLE
Fixed Window API

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#163]
Window API is going to have custom events, Components (to be called Controls), etc.

**Comment by maximusvladimir** [comment]
Window API is on its way. Although development has paused, it will continue after the memory usage has been fixed.

**Comment by abauer** [comment]
what is the problem with memory useage?

**Comment by maximusvladimir** [comment]
PAW is not causing the memory leak (I am pretty sure):

[2/22/2013 2:10:35 PM] Maximus Vladimir:
1. It can't be the Blur. I've disabled it.
2. It probably isn't a thread leak, I haven't done anything to invoke it.
3. It could be a Chunk buffer write error. (Maybe dealing with team ids)
4. It could be the new Entity System (the thing with rotations).
5. There could be a GUI memory leak.
6. It could be that a graphics object isn't being disposed somewhere.
7. ?

I mentioned that during my rant/rage.

**Comment by abauer** [comment]
right...

**Comment by abauer** [comment]
i agree with number 5, possibility and maybe 6

**Comment by maximusvladimir** [comment]
I am pretty sure I got all the nasty #6's.

I am thinking it could be #5 or #3.

I really really would appreciate if @TexasGamer could tell us how many commits he **received** today (on his school computer).

**Comment by abauer** [comment]
well we can get rid of team id's because the color system needs a rewrite
you can't have color in the pavo group, because thats not part of pavo

**Comment by ThomasGaubert** [comment]
@maximusvladimir I'm not sure, but it was quite a few... probably since last class at school, or at least since Friday.

**Comment by maximusvladimir** [comment]
@TexasGamer ok thanks. that should help.
@abauer I don't think it was that, because we've had team ids in there for a while.

**Comment by maximusvladimir** [comment]
So I believe that Window API is almost complete. We've just got to add `MessageBox`, fix a few event problems, and of course add event listeners, and then we should be done.

**Comment by maximusvladimir** [comment]
Adding that too a new issue.
