### ISSUE TITLE
Add snazzy new pause window.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#165]
It's gonna be awesome!

**Comment by maximusvladimir** [comment]
This is going to be sooooo awesome! We need issue #163 closed first.

**Comment by ThomasGaubert** [comment]
How will be pausing? With a button in the interface? Escape has been taken by the global quit system.

**Comment by abauer** [comment]
so six days guise

**Comment by ThomasGaubert** [comment]
_cough_

Technically pausing happens when it's your turn.

**Comment by maximusvladimir** [comment]
I'll reopen this later.
