### ISSUE TITLE
Whales can no longer be placed 

### ISSUE THREAD

**Issue by Matthis5point0** [JPII/NavalBattle#171]
Whales are unable to be placed by the user

**Comment by maximusvladimir** [comment]
According to the **K**ingland **I**nstitute of **L**ongheaded wha **l** es( **KILL** ), a study showed that "criticizing or judging" whales in any given video game, can result in being hunted down by one.

**Comment by abauer** [comment]
this is technically not an issue since nothing will be placed in the final product, the placing of entitys is a debug feature used to test whether they work or not
