### ISSUE TITLE
Pavo rewrite

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#172]
Do not be alarmed my friends!
Не беспокойтесь, товарищи!

There is not going to be any visible change to the game during through this. There is just going to be re-organization to make the code more OOPish (and possibly faster).

Things such as:

``` java
getWorld().getTimeManager().getCurrentMinutes();
getWorld().getWeatherManager().getCurrentWeather();
```

might be refractored to:

``` java
getWorld().getWorldStatus.getCurrentMinutes();
getWorld().getWorldStatus.getCurrentWeather();
```

In the above example, internally TimeManager and WeatherManager should still exist, it's just that a wrapper class will be made to make it easier to access stuff.

More examples of things that could be implemented:
- onResize() for Renderable (occurs when the window is resized)
- The Window API (coming late February 2013).
- LiveThread (will allow faster and easier multithreading for _Pavo_ )
- Comments/Documentation.

**Comment by abauer** [comment]
cool!

**Comment by ThomasGaubert** [comment]
:+1:

**Comment by maximusvladimir** [comment]
PAW is done.
LiveThread is cancelled, due to inconsistencies with thread sharing.

**Comment by maximusvladimir** [comment]
I'm pretty sure this is done for now.

#continuious isse
