### ISSUE TITLE
Different GUI styles

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#173]
Unlike the Windows OS, Pavo Window API (PAW), will have different themes.

**Comment by ThomasGaubert** [comment]
PWA technically*

**Comment by abauer** [comment]
but PAW sounds cooler, Pavo API for Windows?

**Comment by ThomasGaubert** [comment]
:+1:

**Comment by maximusvladimir** [comment]
Well I look at it this way (capital letters indicates where the acronym is coming from):

PAvo Windows api.

**Comment by abauer** [comment]
ok that works also

**Comment by maximusvladimir** [comment]
This isn't needed.
