### ISSUE TITLE
Chunk Errors

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#176]
Chunks that are in the first row & or column error and do not behave properly. They hide themselves and also do not follow the rules for placing entities.

**Comment by maximusvladimir** [comment]
Bro... there's a minor spelling problem.

Anyways, I believe there was already an issue like this. I don't know what happened to it, but it was probably closed "on accident" or moved to a future milestone.

I have spent several hours on this issue on time... when I "fixed" it, it caused imaginary chunks to be displayed occasionally.

Basically it has to do with the [occlusion culling](http://en.wikipedia.org/wiki/Hidden_surface_determination) method I used.

**Comment by maximusvladimir** [comment]
As pointed out above, this issue probably won't be fixed before June, so umm...yeah.

**Comment by abauer** [comment]
1) wheres the spelling?
2) this needs to be fixed... so i guess June better come sometime this month

**Comment by ThomasGaubert** [comment]
I fixed the spelling error a while back.

**Comment by maximusvladimir** [comment]
No comment.

**Comment by abauer** [comment]
more specifically 2)

**Comment by ThomasGaubert** [comment]
Removed wontfix tag.

**Comment by maximusvladimir** [comment]
So water detection is working. Part 1 is fixed.

**Comment by abauer** [comment]
ok if the water issue is fixed we can move this to 0.7 to fix the flashying bit (as that has been an on-going problem)

**Comment by maximusvladimir** [comment]
Ok. Moved. (Actually I didn't move it)

**Comment by abauer** [comment]
I did

**Comment by ThomasGaubert** [comment]
What's the status on this?

**Comment by maximusvladimir** [comment]
"What's the status on this?"

NullPointerException - Issue is not an issue.

**Comment by abauer** [comment]
so moved to 0.8

**Comment by ThomasGaubert** [comment]
This shouldn't be moved past 0.8. This is ridiculous that it hasn't been fixed.

**Comment by maximusvladimir** [comment]
I think I know what the problem with this is.

**Comment by abauer** [comment]
again....

**Comment by maximusvladimir** [comment]
This is bugging me. It is now on my very top priority.

Added `max-top-priority` label to this issue.

**Comment by maximusvladimir** [comment]
Fixed as of commit id 9e68c2ed6f00e085ce3b47d0a8065bd60dd9f14c.

**Comment by abauer** [comment]
ironically the commit is a 404 error

**Comment by abauer** [comment]
and no commit exists int he logs...

**Comment by maximusvladimir** [comment]
I'm syncing now. Please wait one moment, then sync.
