### ISSUE TITLE
Inner workings fix

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#179]
This is probably going to take a while, and I don't plan on doing it yet, but basically I am going to rewrite some inner workings of Pavo. Don't expect to see any visual changes, but there will be some changes to Pavo. I do not believe this directly is causing the memory issue. I think that this fix should help with it though, and could lead to a faster, and more "Java" appropriate program.

**Comment by abauer** [comment]
dat memory error...

**Comment by maximusvladimir** [comment]
^^^ "I do not believe this directly is causing the memory issue."

**Comment by abauer** [comment]
well i blame java (insert newer version number here)

**Comment by maximusvladimir** [comment]
Agreed. I am running:
Version 7, Update 15.

Build 1.7.0_15-b03

**Comment by ThomasGaubert** [comment]
This could be bumped back if need be... afaik it's not breaking things all the time.

**Comment by maximusvladimir** [comment]
Ok. I will do.

**Comment by maximusvladimir** [comment]
Finished this a while back, however this is somewhat of a continuous issue. Expect to see it opened again in the future.
