### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#181]
So I like settings goals.

We will use this "issue" to fix and set those goals.

The following "goals" are passing if they are checked:
- [ ] Memory usage under or at 256 MB.
- [ ] CPU usage between 15% and 30%.
- [x] Disk usage under 10 MB.
- [x] Network utilization not stressful on the client.
- [x] More Game Thing.

Feel free to add some more above.

**Comment by abauer** [comment]
i like.

**Comment by maximusvladimir** [comment]
I don't think these are going to be possible. I don't know yet though.

**Comment by maximusvladimir** [comment]
I think the CPU usage one should be:
"CPU usage below 50% on a quad core processor."
