### ISSUE TITLE
Ship Placement / Mouse Event

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#182]
Something happened, ships can be placed in the top (6?) chunks.

Also the HUD responding to mosueclicks needs refining

**Comment by maximusvladimir** [comment]
Originally, they could be placed in all the chunks (0-64). You are telling me they use to be able to placed in everything except the top 4, and now they can't be placed in the top 6?

**Comment by ThomasGaubert** [comment]
Ships placed in the top six chunks ignore land rules, etc. and can be spawned anywhere.

**Comment by maximusvladimir** [comment]
Yeah... sorry I though that y'all were referring to something else. I will try to take a look.

**Comment by maximusvladimir** [comment]
So I am pretty sure I fixed the issue. (With an exception of course)

**Comment by maximusvladimir** [comment]
So apparently they can be placed, but can't be referenced.

**Comment by abauer** [comment]
ships? or the chunks can't be referenced?

**Comment by maximusvladimir** [comment]
Chunks. This is going to be a tough fix (if there is one).

**Comment by abauer** [comment]
I believe this has been fixed

**Comment by maximusvladimir** [comment]
Yep it's fixed, however chunks will continue to disappear in the top two columns and rows.
