### ISSUE TITLE
JWindow Sizes

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#183]
fixes need to occur to the game window size if we are to offer fullscreen and non-fullscreen as an option

**Comment by maximusvladimir** [comment]
Glorious Leader, you need to re-assign this to Anthony. I didn't design the HUD, therefore it isn't my fault.

**Comment by abauer** [comment]
i didn's say this was your fault, you just mentioned you had an idea for figureing this one out.

**Comment by maximusvladimir** [comment]
Oh ok. I still think Glorious Leader needs to comment here though.... ( @DarkWarHero ).

**Comment by maximusvladimir** [comment]
Technically Max is not responsible for this. This is part of the `Window` class.

Is this what the HUD is suppose to do?:

![image](https://f.cloud.github.com/assets/1757519/232793/f23d3882-8740-11e2-904c-ffa52040ef3b.png)

**Comment by abauer** [comment]
basic idea, but it needs to re size with full screen mode, additionally it needs to work with clients who have different task-bars... (larger, smaller, different position, etc.)

**Comment by abauer** [comment]
found a compromise for now, issue might reappear

**Comment by maximusvladimir** [comment]
Was this anything of my doing, Mr. Bauer?

**Comment by abauer** [comment]
yes, the compromise was, though im sure its not completely done
