### ISSUE TITLE
Update and Announcement Support

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#184]
Support update and announcement alerts.

File would be hosted on this GitHub repo and would point to a URL for more info. The client would store the announcement ID and would only show announcements when the announcement ID is greater than the cached ID.

**Comment by abauer** [comment]
OK had to read this one multiple times...
What kind of file? And you would need to support reading / online mode through roketgamer

**Comment by maximusvladimir** [comment]
Max confused.

**Comment by ThomasGaubert** [comment]
When the game is launched, the LoginWindow will start a thread to grab the following data from the file stored on this repo (update.xml):

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<navalbattle>
    <string name="version_code">5</string>
    <string name="version_readable">0.5</string>
    <string name="update_url">http://github.com/JPII/NavalBattle</string>

    <string name="announcement_code">0</string>
    <string name="announcement_title">This is an announcement</string>
    <string name="announcement_text">Announcement text</string>
    <string name="announcement_url">http://github.com/JPII/NavalBattle</string>
</navalbattle>
```

This data will be parsed as needed and the one of the following will happen:
1. An update is found because the client version code is less than the version code in the file above. The game will alert the user to an update and will have a button to a download link/change log.
2. An announcement is found because the cached announcement code is less than the version code in the file above. The game will display the alert to the user and if defined, a button will appear to open a web page with more info.
3. No alerts are needed to be shown because the above prerequisites have not been met.

If there is no Internet connection or if the user logs in with either RoketGamer/offline mode, the thread will be killed off and no alerts will be displayed, regardless of prerequisites. There could also be a option in LoginOptionsWindow to disable this feature.

Hopefully that explains what I had in mind.

**Comment by abauer** [comment]
awesome, just what i thought you were trying to say, you worded it weirdly in the first post

**Comment by ThomasGaubert** [comment]
Oh yeah, it was a bit rushed.

**Comment by maximusvladimir** [comment]
Oh ok. Much clearer.

**Comment by ThomasGaubert** [comment]
This is sort of implemented, but there are some bugs... I'm still learning how to deal with XML parsing.

**Comment by ThomasGaubert** [comment]
This has mostly been added. I just need to display the buttons when needed.

**Comment by ThomasGaubert** [comment]
Finished a little early! Expect improvements to come in the future...

https://github.com/JPII/NavalBattle/wiki/BroadcastService
