### ISSUE TITLE
Not everything is synced across the network.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#186]

**Comment by maximusvladimir** [comment]
Obvisouly this issue cannot be closed until the majority of the game is finished.
- [ ] Battleships
- [ ] Submarines
- [ ] Window locations
- [ ] Whales
- [ ] Ports
- [ ] Movements

**Comment by abauer** [comment]
- [ ] Aircraft Carriers
- [ ] Turns

**Comment by ThomasGaubert** [comment]
Moved to 0.9 because it'll naturally come later.

**Comment by ThomasGaubert** [comment]
Can this be pushed back since there is more important things to do? This can be taken care of post launch.

**Comment by ThomasGaubert** [comment]
AFAIK multiplayer got stripped out with the addition of StageManager. Should this be closed or removed from all milestones?

**Comment by abauer** [comment]
good question

**Comment by maximusvladimir** [comment]
Well, it shouldn't be too difficult to implement multiplayer, if we have time at the end. I would probably close this issue, since it doesn't really apply anymore.

**Comment by ThomasGaubert** [comment]
Closed for now.
