### ISSUE TITLE
On client disconnect, server can no longer accept other connections

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#187]
1. Server starts.
2. Client connects to server.
3. Client and server play around.
4. Client leaves because he's bored.
5. Another person tries to connect to the server.

The error is at number 5.

**Comment by abauer** [comment]
also those yellow windows that move are awsome

**Comment by maximusvladimir** [comment]
Fixed as of commit id 3201517caa23b0adde62eea7133f2da4dabd9c68.
