### ISSUE TITLE
Old render API is still present.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#191]
The old renderer (like really old), is still present in the code, and needs to be removed to help reduce program size (and to clean up in general).

The old renderer is located at : `com.jpii.navalbattle.renderer` and `com.jpii.navalbattle.renderer.*`.

**Comment by ThomasGaubert** [comment]
What this is not top priority if it is sitting there idle...

**Comment by abauer** [comment]
this is not my responsibility, i have no clue what code you want to keep / get rid of, additionally turn basis is top priority because that is the whole point of this milestone and we've done nothing on it

**Comment by maximusvladimir** [comment]
Whoops, sorry about the comment. I thought this was a different issue. Sorry.

Obviously, this is something that we would ideally finish before we get to 1.0. I don't want the code to disappear quite yet, because there still might be a few things there that might be being used.

I assigned this to Anthony, primarily because I knew that he wanted to do a lot of cleaning up of the code, removing comments, etc.

**Comment by abauer** [comment]
if this has to do with cleaning you can comment on the issue located in the next milestone

**Comment by abauer** [comment]
*moved

**Comment by abauer** [comment]
what is next in this? Since this is our clean-up milestone

**Comment by maximusvladimir** [comment]
It is?

**Comment by abauer** [comment]
yes

**Comment by maximusvladimir** [comment]
Ok. I will clean up some stuff tomorrow during class.

**Comment by abauer** [comment]
ok cool

**Comment by abauer** [comment]
i think this is removed...
