### ISSUE TITLE
Earthquakes

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#195]
I didn't realize we had earthquakes in the game yet...

![earthquake example](https://dl.dropbox.com/u/11164236/navalbattle/nb0.6_03.png)

**Comment by abauer** [comment]
is this a problem?

**Comment by maximusvladimir** [comment]
I believe I fixed it, but it still could be there.

**Comment by maximusvladimir** [comment]
Oh this was fixed a while back. If your computer isn't fast enough to use the fast renderer, then you can't use it. See `isUsingMultithreadedRenderer` in PavoSettings.java for details.
