### ISSUE TITLE
Clients can't control their own PAW windows.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#201]
Only the Server side can move the windows.

**Comment by maximusvladimir** [comment]
Whoops this was suppose to be for 0.7. Moving.

**Comment by ThomasGaubert** [comment]
Since multiplayer for launch is looking unlikely, can we move this way back??

**Comment by maximusvladimir** [comment]
Actually, I was just about to say that this should be irrelevant, as we are still unsure as to how multiplayer should "play out".

**Comment by ThomasGaubert** [comment]
Exactly. Save MP for way later. Moved to 1.1 (this is tentative, depending on when we want to target it).

**Comment by maximusvladimir** [comment]
Honestly, I would have just closed it, and if it becomes "relevant" in the future we can reopen it.

**Comment by ThomasGaubert** [comment]
Ok, closed.
