### ISSUE TITLE
Need a static value for "land" vs water

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#202]
sometimes 5% is used; sometimes 8% is used

**Comment by ThomasGaubert** [comment]
For some reason I thought there was already an issue for this, but I can't find it... 

This needs to be done!

**Comment by ThomasGaubert** [comment]
Found it! #154

**Comment by abauer** [comment]
was a different purpose, that issue was refining the creation of land vs. water, this one is about CON-SIS-TEN-CY (SEEEEEE) in determining whether the tile is land vs water

**Comment by ThomasGaubert** [comment]
Oh, okay.

**Comment by maximusvladimir** [comment]
As of commit id 80c9c68bc0cfd6adad5576d7f47d5b1d5f777977, this should be fixed.
