### ISSUE TITLE
Ship rotation at edges

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#203]
Not sure on status, may be fixed, may be buggy.

**Comment by abauer** [comment]
tested on the right, ships don't move all the way to the right of the map (off by a chunk)

**Comment by abauer** [comment]
would like @maximusvladimir to look at this one...

**Comment by maximusvladimir** [comment]
I will take a look soon.

**Comment by abauer** [comment]
tested at top, not even able to move ships/ships duplicate

**Comment by abauer** [comment]
@maximusvladimir what did you find out? should i reassign the issue to you?

**Comment by maximusvladimir** [comment]
"@maximusvladimir what did you find out? should i reassign the issue to you?"

A. I'm not sure, it was 7 days ago when I said that.
B. No, that is a very bad idea.

**Comment by abauer** [comment]
well if there are no conclusive results from your observation you either need to repeat or get assigned

**Comment by maximusvladimir** [comment]
Ugh-humm, @DarkWarHero.

Sounds like Glorious Leader needs to take a look at the ship rotation on edges.

(I am defiantly not the person suit to this, as I don't even know how to move ships to begin with.)

**Comment by abauer** [comment]
"I don't even know how to move ships to begin with."

this worry's me. you click on the move button on the HUD, and then you click on the yellow space where you want the bow of the ship to move to, right clicking will try to enforce a rotation of the ship; if the ship can't fit in its current position it will auto-rotate.

**Comment by maximusvladimir** [comment]
"the yellow space"

That ain't yeller my friend. It's the color of puke.

I'm mainly having the trouble as to getting it to move to a certain location/

"this worry's me."
Is this because you think that since I am having trouble with this, so will other people??? (Or is it for another reason?)

**Comment by maximusvladimir** [comment]
Last thing for the milestone to close guissse.

**Comment by ThomasGaubert** [comment]
Once this is verified as fixed (anyone???) I will update everything.

**Comment by ThomasGaubert** [comment]
Okay so after actually testing this:
- Ship will get cut off at top edge if rotating to it (need to either not move or shift down to compensate)
- Right edge is borked (see #227)

**Comment by abauer** [comment]
ok fixed the first problem, we can re-evaluate once #227 is fixed
