### ISSUE TITLE
Exclusively use debug window for logging

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#204]
Move all System.out.println() (and similar) to the debug window.

**Comment by abauer** [comment]
hasn't this been done?

**Comment by ThomasGaubert** [comment]
Currently it is disabled. We either need to replace those calls or un-comment the output stream hook.

**Comment by abauer** [comment]
correct...

**Comment by ThomasGaubert** [comment]
Implemented a long time ago.
