### ISSUE TITLE
Find movement bugs

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#207]
Find the bugs associated with movement / moveto method

**Comment by maximusvladimir** [comment]
It has been written: "Thou shall be very careful when modifying moveTo method."

**Comment by ThomasGaubert** [comment]
Stuff I noticed:
- Move limits per turn aren't taken into account yet. (you can move forever)
- Narrow bodies of water in which the ship would need to rotate to fit (if at all) are highlighted as okay. It would be difficult to fix this (especially since rotations would be added soon-ish)

**Comment by abauer** [comment]
hmm you should show me 2), and yes i agree with one, had some questions but the layout is already there.

**Comment by abauer** [comment]
@maximusvladimir iknow; it had to be done so i wanted to know the side-effects (thus the issue)

**Comment by maximusvladimir** [comment]
Oh ok.

**Comment by ThomasGaubert** [comment]
Here's what I was describing:
![Untitled](https://f.cloud.github.com/assets/406075/296407/113272da-94f6-11e2-99ce-ee36753e02ba.png)

**Comment by abauer** [comment]
basically your saying that you should be able to move there... and it won't move.... i agree, and i knew that was a bug, im going to talk with matt and figure some things out and then i will get back to you...

**Comment by ThomasGaubert** [comment]
Right it should move and rotate (or just not allow it all assuming it wouldn't rotate).

**Comment by ThomasGaubert** [comment]
@DarkWarHero What is the status on this?

**Comment by maximusvladimir** [comment]
@DarkWarHero.

**Comment by abauer** [comment]
its done...
