### ISSUE TITLE
HUD doesn't work anymore.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#208]
The HUD doesn't work for Whales anymore as of commit id 00aadf1ce76c8f5a8dc6bd83fa16c064478dbc57.

**Comment by abauer** [comment]
hmm
thats because they are not a Moveable Entity

**Comment by abauer** [comment]
this issue needs to be discussed before action can occur (game logic)

**Comment by maximusvladimir** [comment]
Actually, I didn't click on it the first time. My bad.
