### ISSUE TITLE
Ports have a tendency to merge with ships

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#209]
Detached "head"? ;)

![Capture](https://f.cloud.github.com/assets/406075/296517/bb75e008-94fe-11e2-9fab-74bfe7d76492.PNG)

**Comment by maximusvladimir** [comment]
I understand. The current state and appearance of the ships is purely experimental, and I can assure you, this will not be like this in a few milestones. (Ports will be half on land and half in the water, not floating in the middle :wink:).

**Comment by ThomasGaubert** [comment]
Few milestones = 0.9 = not good enough

Tsk tsk

**Comment by ThomasGaubert** [comment]
This was resolved a long time ago, but was never closed.
