### ISSUE TITLE
Status bar needs to be moved to PAW

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#210]
And no, this does not mean Anthony (or someone else for that matter) copying the render code, and pasting it in an overridden `paint(Graphics2D g);` method.

**Comment by abauer** [comment]
done
(jk)

**Comment by abauer** [comment]
i attempted but i cannot get it to display

**Comment by maximusvladimir** [comment]
I'll look at it later in the week.

**Comment by abauer** [comment]
- [x] Score implemented via ScoreTable (under turn package)
