### ISSUE TITLE
Files that need to be removed.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#211]
- [x] `com.jpii.navalbattle.io.WorldFile.java` (no longer used).
- [x] `com.jpii.navalbattle.io.SettingsReader.java` (replaced by `SettingsIO.java`).
- [x] `com.jpii.navalbattle.io.SettingsWriter.java` (replaced by `SettingsIO.java`).
- [x] `com.jpii.navalbattle.pavo.WorldGen.java` (originally used for Dagen).
- [x] `com.jpii.navalbattle.game.gui.$tmp_swap_cache.java` (originally used for old Window API swapping mechanism).
- [x] `com.jpii.navalbattle.game.entity.component.Breeder.java` (originally used for whale breeding (Whale breeding is outlawed as indicated in Maritime Breeder Code, Chapter 2, Article 9a)).
- [x] `com.jpii.navalbattle.game.entity.component.InteligenceModule.java` (pretty sure this isn't going to be used).
- [x] `com.jpii.navalbattle.game.Game22.java` (pretty sure this isn't going to be used).
- [x] `com.jpii.navalbattle.pavo.FastMath.java` (not needed).
- [x] `com.jpii.navalbattle.pavo.GraphicsLib.java` (not needed).
- [x] `com.jpii.navalbattle.pavo.gui.TestWindowWithNewAPI.java` (was a test for PAW).
- [x] `com.jpii.navalbattle.pavo.io.CompoundedGameStateIO.java` (going to replaced with something far more effective).
- [x] `com.jpii.navalbattle.renderer.*` (EVERYTHING IN HERE IS FOR THE OLD RENDERER EXCEPT `Helper.java` (which happens to be a cousin of `JGHelper.java`).
- [x] `com.jpii.navalbattle.renderer.weather.*` (EVERYTHING IN HERE IS FOR THE OLD RENDERER).
- [x] `com.jpii.navalbattle.renderer.lighting*` (EVERYTHING IN HERE IS FOR THE OLD RENDERER).

Obviously this is not a matter of just deleting files. There might need to be a little changing of code as well.

**Comment by maximusvladimir** [comment]
Part of issue #191.

**Comment by abauer** [comment]
awsome
stuff to do tomorrow/rest of week

**Comment by ThomasGaubert** [comment]
Assigned to @Matthis5point0 so he can do something.

**Comment by Matthis5point0** [comment]
So just run through and delete these files?  Or at least what doesn't need to be saved from ones that state otherwise?

**Comment by abauer** [comment]
check to make sure they are gone
i should have removed them...
