### ISSUE TITLE
HUD event String queue

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#215]

**Comment by abauer** [comment]
now zach needs to display it...

**Comment by maximusvladimir** [comment]
@smeagle42

**Comment by abauer** [comment]
may be combined with the chat program

**Comment by ThomasGaubert** [comment]
I like the combination idea, though PAW will need text input now _cough_

**Comment by abauer** [comment]
not exactly; but i see what you mean, kinda, i was thinking the chat window would be transparent. probably on a different thread to prevent lag (for loops require cpu time...)

**Comment by ThomasGaubert** [comment]
Okay that makes more sense.

**Comment by abauer** [comment]
yeah that's why i had to move this issue and comment out that string stuff, basically i spilt the milk

**Comment by maximusvladimir** [comment]
"probably on a different thread to prevent lag"

There comes a time when putting things on a separate thread is not going to help performance. I believe that our program is using about 23 or 24 threads currently. Microsoft Windows typically limits the number of threads on a 32 bit machine to 25 threads. After this point, Windows (I am pretty sure), begins stacking threads into other ones, which basically means it isn't going to help performance. Also, it depends on how many cpu cores the system has. (Meaning our computers, having 4 cores, can perform certain tasks better than Zach's, with 2 cores, etc).

**Comment by abauer** [comment]
What i meant, was put this into the chat program; and my idea will not work, so a redesign needs to be done

**Comment by maximusvladimir** [comment]
Just have it re-render a buffer, using the onMessageRecieved event for the PavoServer/Client. This is a thread that is not too busy.

**Comment by abauer** [comment]
combine with chat program...

**Comment by maximusvladimir** [comment]
That's a good idea.

#190 .
