### ISSUE TITLE
Team Colors

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#225]
Directed at the Pavo head-lead...

We would like to see Team Colors on the entities;
- [x] Ports
- [x] Battleships
- [x] A.C.'s
- [x] Subs

**Comment by maximusvladimir** [comment]
Ports would be fairly simple to implement. Wait, why is this issue assigned to me?

What's A.C.?

**Comment by abauer** [comment]
Directed at the Pavo head-lead...
and Aircraft Carriers...

**Comment by maximusvladimir** [comment]
Oh awk. I thought A.C. was something else...

I can try to work on ports later on.

The rest is "not going to be an easy fix" (quoting from Iron Man 2).

**Comment by maximusvladimir** [comment]
I mentioned this a long long time ago (in a galaxy far, far away), but if an issue doesn't have any labels/tags, I am not going to see it.

**Comment by maximusvladimir** [comment]
Added team color code. It is nice and fast. Simply call `setTeamColor(byte b)`, and override the `onTeamColorDrawing(Area a)` (it's something like that).
