### ISSUE TITLE
fix casting in HUD

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#226]
casting should happen once

**Comment by abauer** [comment]
ok casting should be complete, but the lag issue still remains; this could be a cause of checking the grid lag or something i have not accounted for. ideally @maximusvladimir could make this super fast if he has time.

(repurpose issue for speeding up the HUD)

**Comment by maximusvladimir** [comment]
Could you give a code example of this?

**Comment by maximusvladimir** [comment]
Or even a line number of what you mean?

**Comment by abauer** [comment]
Example of what the casting issue was; Throughout the update method I would recast display (Entity) to a (MoveableEntity) multiple times; To fix this i created another object move(MoveableEntity) and casted once;

What i would like you to do was look at the update method / entire class and see if you can improve the speed of things happening...

**Comment by maximusvladimir** [comment]
Ok. I will look when I am ungrounded.

**Comment by abauer** [comment]
this has kind of been addressed, re-assigning to @maximusvladimir until he takes a look

**Comment by abauer** [comment]
hud speed has increased considerably; if @maximusvladimir is done we can close this.
