### ISSUE TITLE
Terrain generation error

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#227]
Very serious errors

**Comment by abauer** [comment]
![image](https://f.cloud.github.com/assets/684124/364053/d7103354-a214-11e2-80d3-cd5105fa3483.png)

**Comment by abauer** [comment]
![image](https://f.cloud.github.com/assets/684124/364055/e4c78344-a214-11e2-9a24-7b26eef4e440.png)

**Comment by abauer** [comment]
![image](https://f.cloud.github.com/assets/684124/364057/fcb3d606-a214-11e2-9785-2f05f87aa7d0.png)

**Comment by abauer** [comment]
No exception.

**Comment by maximusvladimir** [comment]
Woah. Looks like tricky Thele put imaginary numbers in our game.

**Comment by abauer** [comment]
why are we checking every update to see if each chuck is visible? shouldn't that only occur when the screen is moved?

**Comment by abauer** [comment]
Yeah, Thats right, I fixed them!

**Comment by maximusvladimir** [comment]
"why are we checking every update to see if each chuck is visible? shouldn't that only occur when the screen is moved?"

The map only updates when an entity changes ids or the world is moved.

**Comment by abauer** [comment]
ok so everytime the whale animates, i am assuming the update is required

**Comment by maximusvladimir** [comment]
maybe.... (looks around nervously).

![ronald](http://25.media.tumblr.com/tumblr_li9s6nAgIQ1qc6x37o1_250.gif)
