### ISSUE TITLE
Login Window

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#231]
Needs a refresh. sometimes does not show all at the beginning of the program

**Comment by abauer** [comment]
![image](https://f.cloud.github.com/assets/684124/369676/fa314558-a2dc-11e2-9b92-694a945dfbc4.png)

**Comment by maximusvladimir** [comment]
I have seen this issue many times.

**Comment by ThomasGaubert** [comment]
Can one of you confirm that it is fixed now? I haven't been able to reproduce the error.

**Comment by ThomasGaubert** [comment]
Closed for now, reopen if the issue reappears.
