### ISSUE TITLE
Entities Fail to Spawn

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#232]
On my desktop machine entities fail to spawn. No exceptions seem to be thrown/caught and the game "runs" as normal.

I'd like to hear @maximusvladimir's thoughts on this.

**Comment by abauer** [comment]
only on your desktop...

**Comment by maximusvladimir** [comment]
And on @smeagle42, entities will spawn on land. My guess is:
1. Due to the differences in speed and performance, the method is being "skipped".
2. Too many threads/ operations in a small time frame. (Kinda has to do with 1.).
3. Something else....?

**Comment by ThomasGaubert** [comment]
This seems to have resolved itself :)

**Comment by ThomasGaubert** [comment]
Fixed when running from a .jar, but not from source (IDE).

**Comment by abauer** [comment]
works from jar afaik
