### ISSUE TITLE
HUD bgcolor

### ISSUE THREAD

**Issue by smeagle42** [JPII/NavalBattle#233]
We need to figure out something for the background then

**Comment by ThomasGaubert** [comment]
Explain what the issue is (UI/UX facts, not subjective thoughts) and suggest a possible solution? Seems fine to me considering everything else that needs attention.

**Comment by maximusvladimir** [comment]
I think that the plain background is far less distracting. I like it.

**Comment by abauer** [comment]
agree with above comments.
