### ISSUE TITLE
Ship Stats

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#234]
@abauer can organize/file away
- Battleship (5 move, 1200 health, 1000 cost)
- Submarine (7 move, 600 health, 1250 cost)
- Aircraft Carriers (3 move, 2000 health, 1250 cost)

**Comment by abauer** [comment]
question; attack ranges both primary and secondary for each?

**Comment by ThomasGaubert** [comment]
What does primary and secondary mean?

**Comment by abauer** [comment]
primary = guns; secondary = missiles (but in case of AC means airstrike)

**Comment by ThomasGaubert** [comment]
Oh okay. I don't know what they are currently, but I think the existing range for the primary attack (guns) is fine. The attack range should be the same for all ships and should only be dependent on the weapon type. Missiles should have a larger range (about 2 more than the guns?).

**Comment by abauer** [comment]
ok cool, glad we discussed that

**Comment by abauer** [comment]
ok primary attacks (guns) have 5 range, secondary attacks (missiles) have 7 range, airstrikes have 9 range

**Comment by abauer** [comment]
implemented
