### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#235]
We had laid out some achievement ideas in the game design document, but considering the current state and capabilities of the game we should make new achievements.

Post your ideas here with a name and a brief description. Ideally we should have at least 10-15.

**Comment by abauer** [comment]
Porkchops: steal porkchops from an enemy port

**Comment by ThomasGaubert** [comment]
**DO NOT EDIT THIS WITHOUT TALKING TO ME FIRST**

Current achievement list: 
1. **Porkchop** - take port
2. **Thrift Shop** - buy from a shop (either)
3. **You Sunk My Battleship** - sink a battleship
4. **Air Superiority** - sink a ship with an airstrike
5. **Syncing Ship** - submit data to RoketGamer
6. **Blank Check** - spend 10,000 points in one stage
7. **Promotion** - complete tutorials
8. **War Bonds** - have 10,000 points
9. **Shock and Awe** - destroy multiple ships in a turn
10. **Lucky Shot** - deflect shot with less than 25% health
11. **It all changed... (Secret)** - lose a ship
12. **...when the fire nation attacked (Secret)** - Lose a port
13. **Another Day (Secret)** - complete a turn
14. **Falling from Trees (Secret)** - lose
15. **Dave (Secret)** - active an easter egg
16. **Naval Superiority (Secret)** - get to round 20
17. **Unstoppable (Secret)** - get to round 30
18. **Commander (Secret)** - get to round 40

_Exact numbers and names subject to change._

**Comment by JVetus** [comment]
Another Day - complete a day cycle.
Dave - happens when a player tries to constantly do an illegal move (or something to that extent)
Falling from trees - Lose your first game after a winning streak

**Comment by maximusvladimir** [comment]
Haha, I like those JR.

**Comment by ThomasGaubert** [comment]
Nice, added them to the list.

**Comment by abauer** [comment]
good additions

**Comment by ThomasGaubert** [comment]
Achievements are in game (as objects) and registered on the server. All that's left is the API (currently working on it) and implementing them into the game (later).

**Comment by ThomasGaubert** [comment]
Achievements are now working for the ones that are actually implemented. RoketGamerWindow is coming... later...

**Comment by ThomasGaubert** [comment]
Someone want to help me implement these?

**Comment by ThomasGaubert** [comment]
All but three have been implemented.

**Comment by ThomasGaubert** [comment]
All have been implemented.
