### ISSUE TITLE
Ships spawning on land and ports not spawning on a dual core processor.

### ISSUE THREAD

**Issue by smeagle42** [JPII/NavalBattle#236]
Dual core processor computers don't spawn ports and spawn entities on land.

**Comment by ThomasGaubert** [comment]
I'm fairly sure this doesn't affect all dual core CPUs.

**Comment by maximusvladimir** [comment]
This has to do with thread execution.

"It's not gonna be an easy fix." - Iron Man 2 quote.
![Iron Man 2](http://www.themarysue.com/wp-content/uploads/2013/01/nick-fury-im2.jpg)

**Comment by abauer** [comment]
unless it affects multitudes of users this really shouldn't be a top-priority

**Comment by ThomasGaubert** [comment]
Might be related to #232

**Comment by maximusvladimir** [comment]
"Might be related to #232"

It is related to 232.

**Comment by ThomasGaubert** [comment]
Well okay.

**Comment by maximusvladimir** [comment]
I didn't intend that to be so harsh. Sorry.

**Comment by ThomasGaubert** [comment]
It's fine, I didn't take it that way.

**Comment by ThomasGaubert** [comment]
Zach, check the current.jar and see if it works. It "fixed" my issues on my desktop.

**Comment by abauer** [comment]
additionally we are going to be distributing via jar so if it works it 'solves' our problem

**Comment by ThomasGaubert** [comment]
@smeagle42 please answer.

**Comment by ThomasGaubert** [comment]
Closing for now.

**Comment by maximusvladimir** [comment]
I just spoke with Mr. Smileg this morning, and he said this issue is still apparent.

**Comment by ThomasGaubert** [comment]
I'm assuming this means with the .jar?

**Comment by maximusvladimir** [comment]
Apparently he is having issues with the jar as well.

Can @smeagle42 confirm this?

**Comment by smeagle42** [comment]
yes

**Comment by smeagle42** [comment]
**Redacted**

**Comment by ThomasGaubert** [comment]
Removed inappropriate comment. Please keep it clean.

**Comment by ThomasGaubert** [comment]
@smeagle42

**Comment by maximusvladimir** [comment]
The root cause of this is multithreading. The direct cause however, is the miss-assignment of tiles. I will look at shortly.

**Comment by maximusvladimir** [comment]
I recently committed what I hoped to be a temporary fix. @smeagle42 do you want to test this fix?

**Comment by ThomasGaubert** [comment]
Obviously not. Moved back and closed.

Reopen if the issue still exists.

**Comment by maximusvladimir** [comment]
I'm just worried it isn't going to work on Schram's computer.
