### ISSUE TITLE
Eclipse Error

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#239]
![image](https://f.cloud.github.com/assets/684124/394117/b46f7d9c-a7ae-11e2-938e-4f6e204f961b.png)

I noticed this error on JR's computer, and now I am getting it also. it is very annoying

**Comment by abauer** [comment]
@TexasGamer @maximusvladimir @DarkWarHero @abauer

**Comment by maximusvladimir** [comment]
Does this error happen all the time? Is it after modifying files? Is it after syncing? Or is it happening randomly? Please provide more detail.

**Comment by abauer** [comment]
random, only in eclipse, usually attempting to run mulitple times fixes it with no code change

**Comment by maximusvladimir** [comment]
Hmmmm.

**Comment by maximusvladimir** [comment]
I forgot to mention that this issue was Anthony's fault.
