### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#24]
A font for the title and/or global game use needs to be decided. If possible, it should be embedded. If not, we need to make sure every user can use that font to prevent layout issues.

The current font (as of creation of this issue) does not display.

**Comment by maximusvladimir** [comment]
I think that we should use bitmap glyphs, so it looks kinda cool. (See http://www.identifont.com/samples/core/Pixelette.gif). Essentially what happens, is when you load the bitmap into memory, you then have an array of BufferedImages, then you crop each character into that array, then you have a method that essential a loop of g.drawImage() 's that draws the text to the buffer you want. If this sounds too complicated, you can see http://www.w3schools.com/cssref/css_websafe_fonts.asp, for a list of fonts available on all systems.

**Comment by ThomasGaubert** [comment]
I like the idea of the glyphs. That pixelated one looks cool.

**Comment by maximusvladimir** [comment]
Ok we are getting somewhere, as of commit id 2b9a39adc552eb13dd9b31f0fff00327277f1743, however I am worried that we may only be able to use the glyphs in the game window itself, which means we still need a font. Also, I may just drop the whole idea of glyphs in favor of a pixelated font, because,well, its just too much effort. (See Helper.java to see what I am talking about.) I really think that this needs to be pushed to the next milestone, but I am going to leave this up to y'all.

**Comment by maximusvladimir** [comment]
Does Nimbus take care of this???

**Comment by abauer** [comment]
no, the mainmenuwindow needs a title font

**Comment by maximusvladimir** [comment]
In the latest commit, Main menu window has a title font

**Comment by ThomasGaubert** [comment]
The title appears to not fit in the space given. See: http://i.imgur.com/pFeTH.png

**Comment by maximusvladimir** [comment]
Even though its not working, it looks sooooo good on Windows 8.

**Comment by maximusvladimir** [comment]
Is this issue closed yet???

**Comment by ThomasGaubert** [comment]
I suppose it can be closed now.

**Comment by maximusvladimir** [comment]
So umm... We have an issue. It turns out that by using a custom font, and placing it in the Font registry can do three of the following things:
1. Have a very slow load.
2. Use large amounts of memory.
3. Slow down g.drawString

**Comment by abauer** [comment]
so i suggest we just use a build in font: and screw anything else

**Comment by abauer** [comment]
so i guess Ill work on finding a cool font to display the title screen in

**Comment by ThomasGaubert** [comment]
As long as it is a sans-serif variant, I am okay with it.

http://en.wikipedia.org/wiki/Sans-serif

**Comment by maximusvladimir** [comment]
`It turns out that by using a custom font`...

Basically what I meant by this is if it is not the default (Arial I think), it will run slow (I am pretty sure).

**Comment by ThomasGaubert** [comment]
So in that case we are "okay"... unless the difference is really that noticeable.

**Comment by abauer** [comment]
Arial or any system font?

**Comment by maximusvladimir** [comment]
I am pretty sure Arial.

**Comment by abauer** [comment]
ok its not a big deal for me

**Comment by abauer** [comment]
fixed font as of 32ddba0a0141d2869fb0bcf3a3ab30ea48bdc265
