### ISSUE TITLE
known issues

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#244]
@Matthis5point0 find more!
- [x] submerge-ing while vertical
- [x] spawning vertically.

**Comment by abauer** [comment]
@abauer will fix

**Comment by abauer** [comment]
- [x] submarine switches teams randomly (vertically)

**Comment by abauer** [comment]
actually jk that last box should be
- [x] submarine vertical is not transparent (sziske problem)

**Comment by abauer** [comment]
fixed all above issues, can you find anymore @Matthis5point0 ?

**Comment by maximusvladimir** [comment]
I like how Anthony has been talking to himself above, despite Matt being assigned this issue.

**Comment by ThomasGaubert** [comment]
Basically like everyday? ;)

**Comment by abauer** [comment]
yeap

**Comment by Matthis5point0** [comment]
Yeah I'll find more bugs don't worry, had a pretty full weekend

**Comment by abauer** [comment]
awsome

**Comment by Matthis5point0** [comment]
Submerge still allows the sub to be destroyed

**Comment by Matthis5point0** [comment]
Ports at top of screen can't be clicked directly, must be clicked one square under port

Hi Jr

**Comment by Matthis5point0** [comment]
If purchasing ships from port shop at top of screen ships spawn in imaginary zone/undrawn zone

Gutentag JR

**Comment by Matthis5point0** [comment]
HELLO THERE JR

Index Out of Bound error while trying to move, AI  can't tell what to do with it's life

**Comment by abauer** [comment]
-/ /[/ /]/ use this in the comment to generate a checkbox (without the slashes)

**Comment by abauer** [comment]
- [x] submarine submerge takes damage (maybe fixed, please re-test)
- [x] port issues for spawning off map
- [x] Max issues for selecting entity on click
- [x] JR's AI array index out of bounds

**Comment by abauer** [comment]
updated and fixed some of these

**Comment by ThomasGaubert** [comment]
Closed because these seem to be done.
