### ISSUE TITLE
fix current.jar

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#245]
fix-it

**Comment by maximusvladimir** [comment]
This is a resource issue. When activity involving entity images settles down, I will step in and do my duty ( :poop: ). I might be able to issue a temporary "fix", then perma fix it later.

**Comment by abauer** [comment]
thats why its .9 issue

**Comment by maximusvladimir** [comment]
Aren't we on 0.9?

**Comment by maximusvladimir** [comment]
Nevermind.

**Comment by abauer** [comment]
no we are waiting on you to finish the '5 minute issue'

**Comment by maximusvladimir** [comment]
I'll fix the five minute issue in 5 minutes.

**Comment by maximusvladimir** [comment]
Pretty much complete.
