### ISSUE TITLE
Button names

### ISSUE THREAD

**Issue by smeagle42** [JPII/NavalBattle#248]
The buttons and button names should be invisible while nothing is selected. Certain buttons and names should show depending on the type of entity that is selected.

**Comment by abauer** [comment]
why? why not just leave them there so that the user is aware of those features but knows they cannot access them?

**Comment by ThomasGaubert** [comment]
I tend to agree with Zach. A better solution would be to hide the text when not needed and display a message saying "select an entity to view information" (or similar) so that way you have the best of both.

**Comment by abauer** [comment]
hey if you have a mock-up that's fine, i can implement it but without one Im not able to perfect the HUD

**Comment by ThomasGaubert** [comment]
mad paint skillz (this is what it would be when not selecting anything

![untitled](https://f.cloud.github.com/assets/406075/461637/2f8acebe-b443-11e2-98f1-71f56f3ad3a7.png)
