### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#32]
Missing icon for Magnifier on OmniMap.
Africa is missing on World icon for OmniMap.

Game icon needs to be in top left corner.
See layout plate for details.

**Comment by maximusvladimir** [comment]
ALSO! THERE SHOULD BE A MAIN ICON FOR ALL THE WINDOWS.

**Comment by ThomasGaubert** [comment]
I can do the main icon.

Possibly unrelated, but the buttons to toggle the map mode should be switched to where the darker option is the one selected (so it looks pressed in). Just my two cents.

**Comment by ThomasGaubert** [comment]
Complete as of now. Reopen this or another issue if there are more to be added.
