### ISSUE TITLE
GUI / Game design (IMAGES INCLUDED)

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#33]
Well, what do we think???

https://dl.dropbox.com/u/11164236/navalbattle0.3layout.png

PS- Its hard to design a GUI for a game that we haven't planned out.

**Comment by maximusvladimir** [comment]
This isn't exactly an issue, but we do need to talk about the game gui design. I am pushing this to the next milestone.

**Comment by ThomasGaubert** [comment]
I agree. We can all make mockups and vote or something...

**Comment by maximusvladimir** [comment]
![New design](https://dl.dropbox.com/u/11164236/navalbattle/nb0.4_01.png)

Here's the newly proposed design.

**Comment by maximusvladimir** [comment]
I think we all know where this is going.
