### ISSUE TITLE
FastMath doesn't work as expected.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#45]
It worked in c++...

**Comment by abauer** [comment]
well sqrt works still, maybe because Java bitshift and C++ bitshift are different?

**Comment by maximusvladimir** [comment]
:lollipop: Haha, no, bitshifts essentially call the platform-dependent native code on the client's system. It is the same with the basic math functions. Because deep down, no matter what, you are still calling basic assembly op codes for math (ADD ,ADC,SUB,SBB,DIV,IDIV,MUL,IMUL,INC,DEC,CMP,SAL,SAR,RCL,RCR,ROL,ROR) (The last 6 are the ones you are asking about.). (I shouldn't say "platform-dependent", rather, I should say "CPU-dependent", (eg. Intel i386, 8086, ARM, etc), because it actually depends on the CPU for the math part).

**Comment by abauer** [comment]
figured, i just wanted an explanation

**Comment by maximusvladimir** [comment]
Ok :smile_cat:. If you have anymore questions, just ask.

**Comment by abauer** [comment]
it would be nice to use this...

**Comment by maximusvladimir** [comment]
Yeah... I have figured out how to make the game fast, I am just worried that once we start putting stuff on the Grid, it is going to get slow. We are really going to need this class.

**Comment by abauer** [comment]
yeah thats probably a big concern to look at

**Comment by maximusvladimir** [comment]
I have implemented something I like to call immortal threads, so it should be able to sync between the game board/terrain si it shouldn't be of any trouble. However I need to talk to yall about locks and off screen updates. Remind me when I get on skype to talk about rhis.

**Comment by abauer** [comment]
relevant to fastmath?

**Comment by maximusvladimir** [comment]
No.... but it relates to the speed of the game... :frowning:

**Comment by abauer** [comment]
ok...

**Comment by maximusvladimir** [comment]
Lol. I don't think we are going to use this anymore.
