### ISSUE TITLE
LoginWindow should save last good username

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#47]
Username will be saved only. Can be disabled in LoginOptionsWindow.

**Comment by maximusvladimir** [comment]
I will work on this.

**Comment by maximusvladimir** [comment]
A settings manager needs to be written. Lets have Anthony do this, since he likes io, and settings.

**Comment by abauer** [comment]
no i don't

**Comment by maximusvladimir** [comment]
I don't want to work on it anymore. Assigned to nobody, and bumped to 0.5, in reality, we don't have to have the saving username until like Beta, but we should have the settings file when we create a settings window.

**Comment by abauer** [comment]
ok can we comment it out so we can run the program now?

**Comment by ThomasGaubert** [comment]
Merged with #57.

**Comment by abauer** [comment]
combined with #67
