### ISSUE TITLE
Toast notifications are bugged with Nimbus

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#48]
Toast notifications have a white line between the text and image. This bug appeared with the addition of Nimbus.

**Comment by abauer** [comment]
hopefully going to take a look at this today

**Comment by ThomasGaubert** [comment]
I have a feeling that it may have to do with Nimbus's background color. The bounds of the text area may not get up against the image area perfectly, so the background leaks though. I may give it a peek in a bit.

**Comment by abauer** [comment]
i tried altering so much stuff; i honestly have no clue as to what the problem is...

**Comment by maximusvladimir** [comment]
I will look into it later. (I'm on mobile right now)

**Comment by abauer** [comment]
again couldn't fix it, a temp fix would be to use a jlabel instead of a text area, at this point the white box doesn't look as bad as first thought

**Comment by ThomasGaubert** [comment]
Finally resolved!
