### ISSUE TITLE
The ability to save chunks and the current state of the grid

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#49]
I will work on the ability to save chunks, and seed data. (I want to save chunks because if I change the world generator, and the person updates the game, the grid might be all messed up). Also you will be able to save the grid and the settings to another file, which will also contain the login data, which is why this is a duplicate.

**Comment by ThomasGaubert** [comment]
Merged with #57.

**Comment by abauer** [comment]
combined with #67
