### ISSUE TITLE
OmniMap not working as intented.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#53]
1. The World Map's red rectangle is off.
2. The Zoom Map is not working at all anymore.
3. Zoom Map needs to have more details in it, such as trees,grass,and waves (may be even animals, not just whales).
4. Zoom Map profiler needs to tick more often.

**Comment by abauer** [comment]
movement needs to occur by omnimap and not as it is now

**Comment by maximusvladimir** [comment]
5;. (as mentioned in abauer's post -- The mouse should be able to move the viewport on the world, in world view mode.)

**Comment by maximusvladimir** [comment]
Part 2 is finished.

**Comment by maximusvladimir** [comment]
6; the mouse on the screen doesn't correlate properly with each other.

**Comment by maximusvladimir** [comment]
Part 6 and Part 4 are fixed as of latest commit.

1,3, and 5 are the only ones left. :smile:

**Comment by abauer** [comment]
looking good

**Comment by maximusvladimir** [comment]
#1 is pretty much fixed, as of commit id 92c0c3b3d74ab5f2b8dddc0ed89f980eb55a0b82.

**Comment by maximusvladimir** [comment]
im not sure why that is bold and large.

**Comment by ThomasGaubert** [comment]
It may had to do with the pound symbol. I fixed it (removed the space).

**Comment by abauer** [comment]
as of now it looks verynice and is functional for this milestone, moved to 0.5

**Comment by maximusvladimir** [comment]
I think we have finished.
