### ISSUE TITLE
Window Builder cannot be used due to Window.java

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#55]
![Bug](https://dl.dropbox.com/u/11164236/navalbattle/bug453.png)

**Comment by abauer** [comment]
it works for me... we might need to look into this

**Comment by ThomasGaubert** [comment]
I ran into this the other day when making the Window class for the first time. In my case it was due to the dynamic logging of the class files.

**Comment by abauer** [comment]
fixed
