### ISSUE TITLE
SettingsAttributes fails to load

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#58]
This should either be fixed before #57 can be implemented.

**Comment by maximusvladimir** [comment]
Is it SettingsAttribute that doesn't work, or is it SettingsReader?

**Comment by ThomasGaubert** [comment]
Well the file appears to not exist, so whatever dealing with that is broken.

**Comment by maximusvladimir** [comment]
It works on mine. I really want to look at one of y'alls computer to see what is going on with it.

**Comment by ThomasGaubert** [comment]
You can mess around with it this afternoon (after school) if you want.

**Comment by maximusvladimir** [comment]
I dident have time today--I saw y'all walking back from practice when I was leaving the parking lot. Do y'all have any idea of what it might be?

**Comment by ThomasGaubert** [comment]
I have no idea why it wouldn't be working, but I know for Hawkridge we stored data in AppData/.hawkridge. We can always try that?

**Comment by abauer** [comment]
i didn't really like that method

**Comment by abauer** [comment]
wrong button
um what about saving online through RoketGamer?

**Comment by ThomasGaubert** [comment]
That is possible, though saving last good username won't be possible. Plus offline mode will create problems.

**Comment by abauer** [comment]
combination of the two?

**Comment by ThomasGaubert** [comment]
I suppose, but the data API won't be ready for quite some time. Might as well do the offline stuff for now and I can hook into it later.

**Comment by maximusvladimir** [comment]
I think that a sync kinda thing will work. I haven't officially started with the saving and loading part. We are looking into save files being about this size: (256_8_100_100_64*48) bytes. I think that al the problem with the setting reader is that it is in that relative directory. Has anyone tried to put the setting file in a affective directory (like C:\folder\settings.ini) and loading it from there.

**Comment by maximusvladimir** [comment]
Oh and the grid file would be like (64_48_entities) bytes.

**Comment by abauer** [comment]
ill take a look into this

**Comment by abauer** [comment]
still doesn't work
and im still not sure how to access a file thats inside a jar that your working with...

**Comment by abauer** [comment]
combined with #67

**Comment by maximusvladimir** [comment]
Umm this issue can't be fixed until we figure out where to start saving data.

**Comment by abauer** [comment]
saving at appdata/.navalbattle
using the same layout / code as hawkridge

**Comment by maximusvladimir** [comment]
Ok, is already fixed, or do y'all want me to do it?

**Comment by maximusvladimir** [comment]
Apparently it hasn't. I will work on this as soon as possible.

**Comment by abauer** [comment]
well it was moved to #67 so post there plz

**Comment by maximusvladimir** [comment]
Lol this issue has like 22 comments.

**Comment by ThomasGaubert** [comment]
Obviously a heated discussion.

**Comment by abauer** [comment]
just a lot of talk

**Comment by maximusvladimir** [comment]
This is on a higher priority than the other load and saving data.

**Comment by abauer** [comment]
well i was trying to combine it into 1 system
but if you feel it needs to be two thats fine: also since i didn't understand pavo was its own package you can just create an i.o. system for pavo;

**Comment by ThomasGaubert** [comment]
So basically there is and/or will be:
1. A IO class for NavalBattle preferences (as described in: https://github.com/JPII/NavalBattle/issues/67#issuecomment-10872877)
2. A separate IO system for pavo for chunk saving, loading, etc.

Right?

**Comment by abauer** [comment]
im thinking thats what needs to happen... because we are going to package pavo so it would make since to package its own IO system: this system could take the path from the constants class

**Comment by maximusvladimir** [comment]
Ok. No problem. Thats what I thought we were doing the whole time. I actually could start working on loading and saving now, but I need entity information first

**Comment by ThomasGaubert** [comment]
Sounds good.
