### ISSUE TITLE
Log to DebugWindow

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#59]
Logs should be written to DebugWindow (versus System.out) for usability and uniformity.

This is more of a management thing to keep in mind as development continues, but upon completion of this issue, the game should be only using DebugWindow.

A good rule of thumb is all pushed code should use DebugWindow. Code that is being worked on can obviously do whatever.

**Comment by abauer** [comment]
looks like all the window hiding and showing works as of now
