### ISSUE TITLE
RoketGamer website is offline

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#60]
RoketGamer, along with every other .co.cc domain appears to be offline. We'll need to look into a new domain or other options.

**Comment by maximusvladimir** [comment]
By the looks of it, it appears that the entire website is gone. I don't think it is coming back anytime soon, either. http://webcache.googleusercontent.com/search?q=cache:http://co.cc/&safe=active&as_qdr=all

**Comment by ThomasGaubert** [comment]
Yeah the domain registrar closed down. I'll look into a new domain :/

**Comment by ThomasGaubert** [comment]
I registered http://roketgamer.com. I will hopefully reupload the site today.

**Comment by ThomasGaubert** [comment]
Okay, logins now work!

**Comment by maximusvladimir** [comment]
Sweet. That's going to look a lot more professional, and it should be more reliable.TexasGamer notifications@github.com wrote:I registered http://roketgamer.com. I will hopefully reupload the site today.

**Comment by ThomasGaubert** [comment]
Thanks. I hope it will be too...
