### ISSUE TITLE
License headers

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#63]
As alpha stage nears conclusion, all files should have the appropriate license header.

**Comment by ThomasGaubert** [comment]
I will complete the headers by this evening.

**Comment by maximusvladimir** [comment]
I will work on pavo tonight too. For now I am just going to use the jpii headers. I still have some un commited changes so I am not ready yet.

**Comment by ThomasGaubert** [comment]
Okay that's fine. I'll leave the renderer and pavo packages alone.

**Comment by ThomasGaubert** [comment]
Done once @maximusvladimir does his package(s).

**Comment by maximusvladimir** [comment]
I finished that a while back.

**Comment by ThomasGaubert** [comment]
Alright cool, completed for now then!
