### ISSUE TITLE
Javadocs

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#64]
As alpha stage nears conclusion, all classes and methods should be fully documented.

**Comment by maximusvladimir** [comment]
Cough cough Max

**Comment by abauer** [comment]
whose doing this and when?

**Comment by ThomasGaubert** [comment]
I can do everything but Max's stuff (as he has a much better idea of what is going on).

Assuming that, I can start whenever... hopefully soon.

**Comment by abauer** [comment]
ok well in that case i guess i can help somewhat : probably gonna start soon also... seeing as this milestone is due in 4 days

**Comment by ThomasGaubert** [comment]
Yeah I can do it between finals or something... I don't think there is a terrible amount (sans the renderer :P)

**Comment by maximusvladimir** [comment]
I am still in the Radical Revamp stage. Files are being deleted and created left and right. I wouldn't expect me to start docing my stuff until a while from now. (Probably 0.5 or 0.6)

**Comment by ThomasGaubert** [comment]
That'll be fine.

**Comment by abauer** [comment]
so i say this milestone applies to everything but pavo / game

**Comment by ThomasGaubert** [comment]
Works for me.

**Comment by ThomasGaubert** [comment]
I will complete the documentation by this evening.

**Comment by maximusvladimir** [comment]
I will worj on pavo documentation some tonight.

**Comment by ThomasGaubert** [comment]
Finished with the exception of the game package (mostly documented beforehand) and possibly the pavo and renderer packages.

**Comment by maximusvladimir** [comment]
Cough cough Pavo cough cough.

**Comment by abauer** [comment]
why is this assigned to me, shouldn't this be for everyone?

**Comment by maximusvladimir** [comment]
Clear the assignee. I need to work especially on Pavo. (The Grid API documentation is almost done).

**Comment by ThomasGaubert** [comment]
Cleared.

**Comment by ThomasGaubert** [comment]
This has been largely addressed with rewrites, etc.

**Comment by maximusvladimir** [comment]
(I'm glad I don't have to do any more documentation. I was really getting tired of typing it all.)

**Comment by ThomasGaubert** [comment]
You should still do it, just as you create methods...
