### ISSUE TITLE
Organize Resources

### ISSUE THREAD

**Issue by smeagle42** [JPII/NavalBattle#68]
Organize resources to be logical. The images are there and sorted, but the references in code need to be changed.

**Comment by maximusvladimir** [comment]
Hold on to yo' horses there for a minute, we can't just change resource paths, without something catastrophic happening. :scream:

**Comment by ThomasGaubert** [comment]
Please explain?

**Comment by maximusvladimir** [comment]
Well I am just saying, that if we do change paths for resources, y'all need to tell me, so I can commit what I have, and stop working, while y'all go through the files and refractor the paths, to prevent something bad from happening.

**Comment by ThomasGaubert** [comment]
Oh okay... it's not very high priority so we'll announce it on Skype so everyone can dump their code, etc. We can probably schedule it for Wednesday or so.

**Comment by abauer** [comment]
agree

**Comment by ThomasGaubert** [comment]
Let's aim for this Saturday to do the code dump. We can assign people to do different packages or one person can do it all.

@abauer @maximusvladimir @smeagle42

**Comment by maximusvladimir** [comment]
Ok. :japanese_goblin:

**Comment by abauer** [comment]
so we started today with the res package: but im assuming this issue involves the redistribution of packages and classes

**Comment by ThomasGaubert** [comment]
Its original intent was for the res package. @maximusvladimir 's other issue on packages is more general.

**Comment by abauer** [comment]
ok so are we done here?

**Comment by ThomasGaubert** [comment]
Yep.
