### ISSUE TITLE
Fatal issue with CommandHandler

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#69]
![Bug #69](https://dl.dropbox.com/u/11164236/navalbattle/bug69.png)

**Comment by ThomasGaubert** [comment]
I'll look into this when I get some free time (hopefully tomorrow).

**Comment by maximusvladimir** [comment]
I haven't seen this issue in a while. It's really weird. Maybe we should close it.

**Comment by ThomasGaubert** [comment]
I haven't encountered it myself.

@abauer and myself were thinking of redoing it anyways.

**Comment by abauer** [comment]
i haven't encountered it, but i do think the command system could use a revamp: its kinda hacky

**Comment by ThomasGaubert** [comment]
Indeed. I tried to take inspiration from Bukkit's system of doing things.

`onCommand (CommandSender sender, Command command, String label, String[] args)`

We can talk about it.

**Comment by abauer** [comment]
ok
well since the commands are set and were only planning to hard code them we can just use strings to pass
this would also reduce some memory useage...

**Comment by ThomasGaubert** [comment]
Right you would have something similar to:

`onCommand(CommandSource source, String command, String args[])`

Where CommandSource is an enum with USER_ENTERED, CODE, etc.

Others make sense.

**Comment by abauer** [comment]
right something like that

**Comment by maximusvladimir** [comment]
Also, you can obtain the stack trace, and parse where it originated from (probably wouldn't be useful though....)

**Comment by abauer** [comment]
but were not getting an error; so what would there be a stack trace of?

**Comment by abauer** [comment]
we could get a stack trace but there would be no relevant information in it

**Comment by maximusvladimir** [comment]
The source. In the professional environment, the stacks actually interact more with the user than people realise.

**Comment by maximusvladimir** [comment]
I haven't seen this issue in a long, long time.
