### ISSUE TITLE
Set up git

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#7]
Get all members up and running on git and GitHub.

**Comment by ThomasGaubert** [comment]
This also includes setting up Gravatars (http://en.gravatar.com/) for easy identification.

**Comment by abauer** [comment]
Of course i get assigned to this.... :P

**Comment by ThomasGaubert** [comment]
Indeed. I can help as needed...

**Comment by ThomasGaubert** [comment]
:O

**Comment by abauer** [comment]
Just joking:
Ready to program: Abauer, Texasgamer, Max
Needs Fixing: Matt W, Zach M, JR

**Comment by ThomasGaubert** [comment]
Everyone seems to have GitHub working, but Eclipse still needs to be installed/setup.

**Comment by abauer** [comment]
Not sure that everyone even has GitHub...

**Comment by ThomasGaubert** [comment]
Closing this as we can figure it out on a case by case basis.
