### ISSUE TITLE
Renderer is being rewritten.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#70]
Issues with previous renderer:
1. Very little OOP
2. Somewhat buggy
3. Code not clean
4. Not optimizable (and not optimized for that sake).
5. Chunks were static. (A BIG issue, led to 10, 9, 3, and 1).
6. The Day/Night cycle overhead was handled per chunk, and should be dependent on the entire screen.
7. Onions have layers... Ogres have layers. The Game.java renderer didn't have a proper layering system.
8. The Day/Night cycle code was thrown in some obscure corner of the game.
9. The Game.java file was becoming to big. 
10. Do to the fact that the code was unorganized, multithreading never worked properly.
11. Just to sum it up, Red cars are to green cars as GameThing is to com.jpii.navalbattle.renderer.

**Comment by ThomasGaubert** [comment]
:+1:

**Comment by maximusvladimir** [comment]
70% left to go, until we can get back to where we were.

**Comment by abauer** [comment]
:+1:

**Comment by maximusvladimir** [comment]
:+1:

60% left to go...

LOL no. 11 is my favorite.

**Comment by abauer** [comment]
11 is very funny
laughed so hard

**Comment by ThomasGaubert** [comment]
:+1:

**Comment by maximusvladimir** [comment]
Only OmniMap, more terrain details, and a few other things are missing.

45% left to go.

**Comment by maximusvladimir** [comment]
30% left to go.

I will have to say, I am _extremely_ impressed by how much has come along between rewriting it and now.

**Comment by maximusvladimir** [comment]
20% left to go.

OmniMap work, Grid work, and some small details.

I will have to say, I am **extremely** impressed by how much has come along since the last time I commented on this issue.

**Comment by maximusvladimir** [comment]
Due to the current state of the game, i think we completed this, alonnnng time ago.
