### ISSUE TITLE
Profile application

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#71]
Using a program such as [JProfiler](http://www.ej-technologies.com/products/jprofiler/overview.html), we need to check for any glaring issues such as memory leaks, etc.

The program is nice, though unfortunately not free so it'll have limited use as development continues.

**Comment by maximusvladimir** [comment]
There is a REALLY nice one included on your system, that's right folks, it's free and already included.

C:\Program Files\Java\jdk1.7.0_02\bin\jvisualvm.exe.

I use it ALL the time, and it is really nice.

**Comment by maximusvladimir** [comment]
PS- Your path may be slightly different than indicated above.

**Comment by ThomasGaubert** [comment]
Thanks for the heads up, I'll probably use that.

**Comment by abauer** [comment]
so fixed?

**Comment by ThomasGaubert** [comment]
No, this task was to indicate that we need to profile it at the conclusion of this milestone and/or during development to work memory usage, etc. down.
