### ISSUE TITLE
Load screen for the actual game.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#72]
I admit it, I may not be able to write code that operates the fastest, however I have thought in advance for the code I am currently writing for the renderer, and I would like to say it would be very cool to have a load screen for the loading of the game (while everything is generating), even though it only takes a few seconds. I have added a method in WorldGen.java (getPercentComplete()), which will indicate the percent complete of the generation (since it is multithreaded). We should provide the percent to a gui, which will have a progress bar indicating how far we are, from having the user at their game.

**Comment by maximusvladimir** [comment]
As of commit id 5e87999eec21fc18d3b7a1c30d8e55713cf85e2f, this is partially fixed. It doesn't look that good though... :worried:

**Comment by maximusvladimir** [comment]
As of latest commit, I have implemented a smoother progress bar. :octocat:

**Comment by ThomasGaubert** [comment]
Looks good. I may add an animation or something to spruce it up later.

**Comment by maximusvladimir** [comment]
No longer applicable.
