### ISSUE TITLE
Here's an idea for OmniMap

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#74]
Lets put the MiniZoomMap in a circular magnifying glass. What would happen, is if the mouse would hover over a point for ~1 or ~2 seconds, a magnify orb would appear with that area zoomed in. (Kinda like when you hold your finger down on a text input gui component on Appl\* iO\* devices). The OmniMap in the upper corner would show only the map of the world.

Idk. It's just an idea.

**Comment by ThomasGaubert** [comment]
Possibly, though it could get annoying. Why not right click or something else instead?

**Comment by maximusvladimir** [comment]
You're right. I like right clicking better.

**Comment by maximusvladimir** [comment]
This isn't essential, and it is kinda pointless, so this is going to be cancelled.
