### ISSUE TITLE
The screen should be able to be moved by an action being undergone on a entity that is focused on.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#76]
I figured a cool way to do it.

**Comment by maximusvladimir** [comment]
Do y'all know what I mean by this?

**Comment by maximusvladimir** [comment]
I think that this idea is going to be replaced by the GridedWindows. Idk though.

**Comment by maximusvladimir** [comment]
Although this is going to be replaced by GridedWindows, it still will be in the game.

**Comment by abauer** [comment]
i think the Grided Windows (the ones with the big lines right?) should be fine; though this would be a cool feature if implemented.

**Comment by maximusvladimir** [comment]
GridedWindows are the ones that have the red arrows that point to grid locations. (Sorry its kind of decieveing)

**Comment by abauer** [comment]
no i got it. Looks good

**Comment by abauer** [comment]
Ai should be able to move the screen also

**Comment by maximusvladimir** [comment]
I would find that somewhat annoying though...

**Comment by abauer** [comment]
@maximusvladimir in correlation with #143 what is the status of this one?

**Comment by maximusvladimir** [comment]
I think these are the same issues.

**Comment by abauer** [comment]
so close one> and finish the other?

**Comment by maximusvladimir** [comment]
How about we close all of the issues. ;)

**Comment by maximusvladimir** [comment]
This has been done. The double click has not.

**Comment by abauer** [comment]
awesome!

**Comment by abauer** [comment]
unless the coordinate parameters are in place, reopening

**Comment by maximusvladimir** [comment]
Ughhhh....

**Comment by maximusvladimir** [comment]
I am pretty sure this is fixed.

**Comment by abauer** [comment]
still not done.... ugh #5minutes

**Comment by ThomasGaubert** [comment]
Status of this?

**Comment by abauer** [comment]
This is top priority and @maximusvladimir has said he can fix it, I am sill of the opinion that this will not take 5 minutes (as 5 minutes has already been spent) and that work has halted on this. This issue is the road block to finishing the game.

**Comment by maximusvladimir** [comment]
"This issue is the road block to finishing the game."

Not necessarily. The fix to this issue is simple, however I have not had the paraphernalia to fix it. I understand what the problem is.

**Comment by abauer** [comment]
you also had a weekend to fix it

**Comment by maximusvladimir** [comment]
1. I have had a busy weekend.
2. I have been working on my other computer extensively.
3. Running the NavalBattle project on a little notebook is fairly difficult to manage (not sure why).

**Comment by abauer** [comment]
ok i understand. but this issue needs to be completed if we are to move forward.

**Comment by maximusvladimir** [comment]
Fixed as of commit id 2468dcabad6d1ab81b4b0bae0d8f2981223eb7fc.

Note that the window does not perfectly center on the tile, thanks to chunk positioning and floating point problems.

**Comment by abauer** [comment]
ok that's fine but this should be working... if its not there may be some complications

**Comment by maximusvladimir** [comment]
"if its not there may be some complications"
What could that be?

"thanks to chunk positioning and floating point problems."
There ain't much I can do about that. I think that it works fine enough.

**Comment by abauer** [comment]
if it gives a relative centering of the screen (variance by ~10 is acceptable) then this should be fine

**Comment by maximusvladimir** [comment]
"~10"

10 what?

**Comment by abauer** [comment]
10 pixels

**Comment by maximusvladimir** [comment]
Hahahaha. It's usually off by about 0-2.5 chunks. It generally is towards the bottom of the screen. You can also specify a speed.
