### ISSUE TITLE
There are ALOT of packages. Could we consider clearing some out???

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#78]
I can clear out com.jpii.navalbattle.renderer, once I finish Pavo.

Y'all can delete com.jpii.dagen, com.jpii.dagen.processing, com.jpii.dagen.test, and com.jpii.dagen.vegetation. (MBBT).

Anything that y'all think could think of?

**Comment by ThomasGaubert** [comment]
Is the problem being there are more sub-packages than necessary? (Anything beyond com.jpii.navalbattle.parent)

**Comment by abauer** [comment]
i don't think the problem is a lot of packages (they create organization) i think there are some things that are packaged incorrectly and some packages that are not needed

**Comment by ThomasGaubert** [comment]
I agree with @abauer. We can possibly discuss it whenever we decide to do the "check up" chat.

**Comment by maximusvladimir** [comment]
Like I said;

Y'all can delete com.jpii.dagen, com.jpii.dagen.processing, com.jpii.dagen.test, and com.jpii.dagen.vegetation. (MBBT).

There might be a few others that we can optimize.

**Comment by abauer** [comment]
having a tree flow diagram of the packages w/classes contained in them can help us organize during our checkupchat

**Comment by maximusvladimir** [comment]
Does anyone have a copy Microsoft Office Visio??? Lucid charts is fine, but I really like Visio.

**Comment by ThomasGaubert** [comment]
Sadly, no I don't.

**Comment by ThomasGaubert** [comment]
Work will be carried out here: https://docs.google.com/spreadsheet/ccc?key=0AmzQhfjZvZcwdFdTdVJtMnFWaFljNld5eDAtaVZCNkE

cc: @maximusvladimir @abauer @smeagle42 @DarkWarHero @smeagle42

**Comment by ThomasGaubert** [comment]
Closed as this is addressed in #98
