### ISSUE TITLE
Buggy in-game windows

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#85]
In-game windows are slightly buggy. The map will sometimes get selected instead.

**Comment by maximusvladimir** [comment]
Im thinking we should just remove them...

**Comment by ThomasGaubert** [comment]
Possibly... though I would like to see some kind of popup framework (maybe it just cannot move and opens in the center?).

Profile cards could be the same when another entity is clicked.

**Comment by abauer** [comment]
either way works...

**Comment by maximusvladimir** [comment]
Three words banned from NavalBattle:
1. GameThing (Lets just rename NavalBattle to NavalThing)
2. Cards (reminds me too much of Risk....)
3. JGHelper (the worst catastrophe in the professional world since the Great Depression).

**Comment by abauer** [comment]
lol to 3

**Comment by maximusvladimir** [comment]
lol indeed

**Comment by ThomasGaubert** [comment]
Heh.

"Lets just rename NavalBattle to NavalThing"

Wait really?

**Comment by maximusvladimir** [comment]
(sarcasm)

**Comment by abauer** [comment]
are u sure your being sarcastic... i mean that should fix all our problems and make the game work with all the features instantly... At least that's what i've been taught

**Comment by ThomasGaubert** [comment]
Plus it works everywhere! :wink:

**Comment by maximusvladimir** [comment]
The reason this bug is still present, is that the updator can not keep up with the render. This should be classified as another bug.

**Comment by maximusvladimir** [comment]
This should be linked to issue #89.

**Comment by maximusvladimir** [comment]
I think this is as good as it's gonna get.

**Comment by ThomasGaubert** [comment]
Alright, closed.
