### ISSUE TITLE
Toast notifications display below active windows

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#86]
This is mainly a problem when playing the game in "full screen". We may want to look into rendering a separate toast notification when the game is being played (calls to the utility would be redirected as needed, or something...).

**Comment by abauer** [comment]
well considering you should never have the game open ontop of the toaster... unless you use toaster for achievements... so nm.

**Comment by ThomasGaubert** [comment]
Achievements and friend notifications (and whatever else we decide to use) won't be viewable in-game... though technically they are there.

**Comment by abauer** [comment]
right i realized that halfway through typing and was too lazy to delete

**Comment by maximusvladimir** [comment]
I think I can fix this.

**Comment by maximusvladimir** [comment]
The fullscreen issue should be fixed in commit id 326376a599bbf9ad5a0adf5a3457a47cc38b0ade. Can somebody let me know if it worked?

**Comment by ThomasGaubert** [comment]
I'll check it soon...

**Comment by maximusvladimir** [comment]
Lol I am almost certain I fixed it, but now when you press the start button on your keyboard, it glitches up. According to  Microsoft's Application Policy, it is not legal to prevent the user from accessing Window Security Menu, or the Start Menu via the Start button on the keyboard.

**Comment by abauer** [comment]
well guess thats violated... anyway i am planning on doing some tests myself anyway

**Comment by maximusvladimir** [comment]
I am going to play with Toaster for a while, okay?

**Comment by ThomasGaubert** [comment]
Sounds good to me.

**Comment by maximusvladimir** [comment]
This is not a priority, is it? And hasn't it been fixed?

**Comment by ThomasGaubert** [comment]
I haven't noticed it myself recently. Closed!
