### ISSUE TITLE
Critical issue with chunk render

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#87]
The chunk render is rendering more chunks than necessary.

**Comment by abauer** [comment]
possibly a problem

**Comment by maximusvladimir** [comment]
This is worse than it seems. I am not talking about Chunks rendering offscreen, I am talking about Chunks rendering underneath other chunks. This is why the edge of the map is black.

**Comment by abauer** [comment]
wow, thats bad

**Comment by maximusvladimir** [comment]
Looks like this issue won't be fixed for a while...

**Comment by maximusvladimir** [comment]
Whoops, I accidentally assigned this to Zach.

**Comment by abauer** [comment]
lol : that could not be good #thridrewriteftw

**Comment by maximusvladimir** [comment]
Fixed, as of several commits yesterday.

**Comment by maximusvladimir** [comment]
This is definitly fixed as of commit 95a698b626e8f357316a20bf35008a39f1da2540.
