### ISSUE TITLE
Fullscreen after Windows key fails

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#88]
When in fullscreen, the Windows key does work (the start screen/menu is shown), but afterwards attempts to put the game back into fullscreen mode with F11 fail.

Haven't tested this on Windows 7, so it may be a Windows 8 thing.

**Comment by maximusvladimir** [comment]
Thanks for reminding me! I forgot to fix this (I knew it was there).

**Comment by maximusvladimir** [comment]
is this still a problem?

**Comment by ThomasGaubert** [comment]
Yep! It works really well.
