### ISSUE TITLE
Update inconsistancies

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#89]
I have noticed that there are often large changes in game speed depending on how much is running in the background.

When I refer to _game speed_, I am referring to how often the game updates.

After creating the optimizations yesterday (12/15/2012), I noticed a HUGE improvement in speed. The _draw time_ is around 16ms in fullscreen, previously being around 50ms in fullscreen. With the 800x600 mode, it is now around 7ms, previously around 19ms. Additionally, the _game speed_ has improved significantly.

The issue is, depending on how much is running in the background, depends on how often the game updates. (E.g., on a faster machine, the Day/Night cycle may last 1 minute and 40 seconds, and on a slower machine it might be around 2 minutes and 20 seconds.

Once again, the game itself is very fast (moving around has zero lag on my poor PC), its just the synchronization between the game and the clock.

**Comment by maximusvladimir** [comment]
I am also beginning to notice that the longer you have your computer running, the slower the draw time becomes.

**Comment by maximusvladimir** [comment]
Just ran an official test--- The Day/Night cycle (24 game hours) lasts 1 minute and 40 seconds. Could somebody run it on another computer, and see if that what they get?

**Comment by maximusvladimir** [comment]
Also, I think that the renderer is not a problem at all anymore. I am not complaining about a 6ms draw time in full screen at all.

The main issue is the updator. I don't understand why it is not staying in sync with the renderer.

**Comment by ThomasGaubert** [comment]
I got about 1:44, give or take a few seconds.

Here's a video of it: http://youtu.be/BK7FwjOeZQo

**Comment by maximusvladimir** [comment]
I am 99% sure I have it figured it out, therefore, this issue is closed.
