### ISSUE TITLE
Omnimap becomes monomap

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#92]
Since the renderer and stuff is soooo fast now, why don't we just put the trees and grass in the actual world, instead of the omnimap, making omnimap only have the duty of showing the entire world.

**Comment by maximusvladimir** [comment]
The actual file name wouldnt change, fyi.

**Comment by maximusvladimir** [comment]
abauer says Ok

**Comment by ThomasGaubert** [comment]
dat spelling :-1:

**Comment by maximusvladimir** [comment]
Almost complete with this.

**Comment by maximusvladimir** [comment]
Pretty much done with this.
