### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#94]
Just at a curiousity, why is there a class named Window? There is already a java window class (java.awt.Window).

**Comment by ThomasGaubert** [comment]
It takes care of some defaults, such as icons, sizing, and the global listeners.

**Comment by abauer** [comment]
we can rename it if its a problem

**Comment by maximusvladimir** [comment]
It shouldn't be a problem, unless we start using those sub windows things.
