### ISSUE TITLE
To preserve memory, grid entities should be null.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#96]
We could reduce memory usage if we made all grid entities null, however we would lose the ability to detect mouse movement, and we would be unable to add Steve to the grid.

**Comment by ThomasGaubert** [comment]
This would be okay as I don't see a case in which we need mouse movement.

**Comment by abauer** [comment]
agree with @TexasGamer

**Comment by maximusvladimir** [comment]
Ok. No problem. I set this for 0.6, so that I can continue to test stuff, basically this means that, this is one of those long term things.

**Comment by maximusvladimir** [comment]
Taken care of.
