### ISSUE TITLE
Refractor

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#98]
The NavalBattle stuff needs to get out of Pavo's Entity Manager, and moved to a NavalBattle related package, inheriting Pavo's EntityManager.

**Comment by ThomasGaubert** [comment]
Piggybacking on this with @abauer. The current plan would be to:
- Move Window "engine" to GameKit and implement
- Implement DebugWindow and LocalizationManager from GameKit - see #94 and #97
- Move RoketGamer to a separate repo (TexasGamer/RoketGamer-Java) and implement as a library

I may be missing something, but regardless we'll need to discuss it.

**Comment by ThomasGaubert** [comment]
Using the [new checklist feature](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments):
- [x] Move Window "engine" to GameKit
- [x] Implement aforementioned Window "engine" (see #94)
- [x] Implement DebugWindow and LocalizationManager from GameKit (see #97)
- [x] Move RoketGamer to a separate repo (TexasGamer/RoketGamer-Java)
- [x] Implement this new RoketGamer repo as a library

Feel free to add more as I am sure there are some that I cannot think of or see as useful.

**Comment by abauer** [comment]
SOOOOO COOL!!!! now we can put this in other issues also

**Comment by ThomasGaubert** [comment]
It's like issue-ception. :octocat:

**Comment by maximusvladimir** [comment]
Inception was a great movie :ghost:

**Comment by abauer** [comment]
so when is this taking place?

**Comment by maximusvladimir** [comment]
0.9ish

**Comment by abauer** [comment]
how about 0.8?

**Comment by maximusvladimir** [comment]
Actually I think it was 0.8.

**Comment by abauer** [comment]
ok well you said 0.9

**Comment by maximusvladimir** [comment]
Actually I said 0.9ish, because I was unsure. It doesn't really matter though. Either one would work.

**Comment by maximusvladimir** [comment]
So I think this was finished over a week ago.

**Comment by ThomasGaubert** [comment]
Technically we still need to implement the GameKit components into the game, but the classes are there to be implemented.

**Comment by maximusvladimir** [comment]
Oh I thought that was done.... awkward on my part.
